(function(g){var window=this;'use strict';var $Sf=function(a,I,U){g.f(function(e){a.V=g.lk(I,U);g.Aj(e)})},TN=function(a){a.isActive()||a.start()},iXz=function(a,I){return I?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},L5z=function(a){return g.eI(a)||a.N("web_enable_caption_language_preference_stickiness")},gOf=function(a,I){var U=new g.Mh;
U.languageCode=a.languageCode;U.languageName=a.languageName;U.name=a.name;U.displayName=a.displayName;U.kind=a.kind;U.isDefault=!1;U.V=a.V;U.isTranslateable=a.isTranslateable;U.vssId=a.vssId;U.url=a.url;U.translationLanguage=I;a.xtags&&(U.xtags=a.xtags);a.captionId&&(U.captionId=a.captionId);return U},cmm=function(a,I){var U,e,T;
return g.f(function(C){if(C.L==1)return U=a+"|"+I,g.l(C,g.eX(),2);if(C.L!=3){e=C.V;if(!e)throw g.Wz("gct");return g.l(C,g.y3(e),3)}T=C.V;return C.return(T.get("captions",U))})},W5D=function(a,I,U){cmm(a,I).then(function(e){e&&U(e.trackData,new g.Mh(e.metadata))})},XPz=function(a){if(!lRf.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(BbQ,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Pj8=function(){var a=void 0;
a=a===void 0?{}:a;var I="suggest_correction"in g.Izm?g.Izm.suggest_correction:"Edit caption";I=I||"";var U={},e;for(e in a){U={wX:U.wX};U.wX=e;var T=function(C){return function(){return String(a[C.wX])}}(U);
I=I.replace(new RegExp("\\$\\{"+U.wX+"\\}","gi"),T);I=I.replace(new RegExp("\\$"+U.wX,"gi"),T)}return I},pPG=function(){return g.EV("yt-player-caption-display-settings")},CL=function(){this.segments=[]},fRJ=function(a,I){var U=g.Po(a.segments,I);
U>=0||U<0&&(-U-1)%2===1||(U=-U-1,U>0&&I-a.segments[U-1]===1&&U<a.segments.length&&a.segments[U]-I===1?(g.VG(a.segments,U),g.VG(a.segments,U-1)):U>0&&I-a.segments[U-1]===1?a.segments[U-1]=I:U<a.segments.length&&a.segments[U]-I===1?a.segments[U]=I:(g.Wo(a.segments,U,0,I),g.Wo(a.segments,U+1,0,I)))},YEG=function(a,I,U,e,T,C){g.S.call(this);
this.policy=a;this.player=I;this.Va=U;this.D=e;this.U=T;this.j=C;this.J=new CL;this.Y=-1;this.B=this.L=this.V=null;this.gw=0;this.C=new g.Dy(this.eJ,1E3,this);this.events=new g.Ru(this);g.E(this,this.C);g.E(this,this.events);this.events.G(I,"SEEK_COMPLETE",this.T1);this.T1();this.eJ()},OXJ=function(a){return a.V&&a.V.Y?a.V.Y+a.player.Dl()<a.player.getCurrentTime():!1},SEj=function(a,I){if(a.policy.No&&a.player.An()){var U=g.IK(I,a.policy,{});
U.set("pot",a.player.An());U=U.MJ()}else U=g.IK(I,a.policy,{}).MJ();var e={format:"RAW",withCredentials:!0};if(a.policy.Ux){e.method="POST";var T=I.J;T&&Object.keys(T).length>0?e.postBody=g.sH(T,g.tX):e.postBody=(0,g.XN)([120,0])}a.U&&(e.responseType="arraybuffer");var C=++a.gw,r=(0,g.w)();a.B=g.pj(U,e,3,100).then(function(q){if(a.policy.Vl&&C%100===1){var x=(0,g.w)();a.player.R$("caprsp",{rn:C,ms:x-r,kb:(q.xhr.responseText.length/1024).toFixed()})}a:{q=q.xhr;a.Ox();if(a.L){var Z=!(a.U?q.response:
q.responseText)||q.status>=400;if(x=g.Rag(q)){q=g.IK(a.L,a.policy,{});a.L.rK(q,x);SEj(a,a.L);break a}Z?a.player.R$("capfail",{status:q.status}):(a.player.zQ().Qm("fcb_r"),x=a.L.nO[0].pO,a.D!=null&&a.Y!==x&&(Z=a.L.nO[0],a.U?a.D(q.response,(Z.startTime+a.player.Dl())*1E3):a.D(q.responseText,(Z.startTime+a.player.Dl())*1E3),a.Y=x))}a.L=null;a.B=null}}).L$(function(q){a.L=null;
a.B=null;var x;a.player.R$("capfail",{rn:C,status:(x=q.xhr)==null?void 0:x.status})});
a.L=I;fRJ(a.J,a.L.nO[0].pO)},rQ=function(a,I){g.bD.call(this,I);
this.V=a;this.K=I;this.B=null;this.Y=!1;this.logger=new g.bh("caps");this.C=g.Bj(this.K.X())&&!this.V.isManifestless},ymd=function(a,I){var U=[],e;
for(e in a.V.V)if(a.V.V.hasOwnProperty(e)){var T=a.V.V[e];if(g.uD(T,I||null)){var C=T.info.id,r=C,q="."+C,x="",Z="";if(T=T.info.captionTrack)C=T.languageCode,r=T.displayName,q=T.vssId,x=T.kind,Z=T.id;else{T=C;var t=g.itI.get(T);t==null&&(t=Gnj[T]||Gnj[T.replace(/-/g,"_")],g.itI.set(T,t));T=t;r=T||r}U.push(new g.Mh({id:e,languageCode:C,languageName:r,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:q,kind:x,captionId:Z}))}}return U},EOQ=function(a,I){return I!=null&&I in a.V.V?a.V.V[I]:null},
dSo=function(a,I,U){var e=[],T;
for(T in a.V.V)if(a.V.V.hasOwnProperty(T)){var C=a.V.V[T];if(g.uD(C,U||null)){var r=C.info.captionTrack;r&&r.languageCode===I&&e.push(C)}}return e.length?e[0]:null},Hs=function(a,I,U,e,T,C,r,q,x,Z){var t=Z.isInline()&&!0,n={};
Object.assign(n,I);Object.assign(n,a.params);Object.assign(n,U);var K={};Object.assign(K,I.Ao);a.params.Ao&&Object.assign(K,a.params.Ao);Object.assign(K,U.Ao);t&&(n.windowOpacity=.6,K.backgroundOpacity=0);n.Ao=K;var b=n.mH===1,J=[{W:"span",T:"captions-text",S:{style:"word-wrap: normal; display: block;"}}],V,M,c;(q=q.S8("caption_edit_on_hover")&&((V=Z.getVideoData().getPlayerResponse())==null?void 0:(M=V.captions)==null?void 0:(c=M.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand))&&
J.unshift({W:"button",T:"caption-edit",S:{tabindex:"0","aria-label":Pj8()},Z:[{W:"svg",S:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},Z:[{W:"path",S:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.F.call(this,{W:"div",T:"caption-window",S:{id:"caption-window-"+a.id,dir:b?"rtl":"ltr",tabindex:"0",lang:n.lang},Z:J});var W=
this;this.C=[];this.dw=!1;this.L=a;this.zt=this.Ux=null;this.playerWidth=C;this.playerHeight=r;this.D=null;this.maxWidth=C*.96;this.maxHeight=r*.96;this.V=n;this.IF=U;this.gw=I;this.J=this.Ws("captions-text");this.hN=this.J.style.getPropertyValue("box-decoration-break")!==""||this.J.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.a$=RtQ(e,T,C,r);this.F1=x;q&&(this.Y=this.Ws("caption-edit"),this.G(this.Y,"click",function(){W.F1()}));
this.type=0;this.fO=this.a$*wPD(K);this.E7=t;a=new g.O9(this.element,!0);g.E(this,a);a.subscribe("dragstart",this.q4,this);a.subscribe("dragmove",this.yU,this);a.subscribe("dragend",this.rl,this);this.XX=this.Z6=this.i5=this.xa=0;a="";this.V.windowOpacity&&(a=XPz(this.V.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.V.windowOpacity+")");I={"background-color":a,display:this.V.isVisible===!1?"none":"","text-align":F5z[this.V.textAlign]};this.hN&&(I["border-radius"]=a?this.fO/8+"px":"");(this.B=
this.L.params.mH===2||this.L.params.mH===3)&&mSd(this,this.element);g.Gr(this.element,I);if(t){var B;(B=this.element.parentElement)==null||B.style.setProperty("--caption-window-color",a)}switch(this.V.Tw){case 0:case 1:case 2:g.x5(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.x5(this.element,"ytp-caption-window-bottom")}},mSd=function(a,I){var U="vertical-rl";
a.V.Mi===1&&(U="vertical-lr");g.k5&&(U=U==="vertical-lr"?"tb-lr":"tb-rl");g.Gr(I,"-o-writing-mode",U);g.Gr(I,"-webkit-writing-mode",U);g.Gr(I,"writing-mode",U);g.Gr(I,"text-orientation","upright");g.x5(I,"ytp-vertical-caption");a.L.params.mH===3&&(g.Gr(I,"text-orientation",""),g.Gr(I,"transform","rotate(180deg)"))},wPD=function(a){var I=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)I*=.8;return I},QW4=function(a,I){var U={},e=I.background?I.background:a.V.Ao.background;
if(I.backgroundOpacity!=null||I.background){var T=I.backgroundOpacity!=null?I.backgroundOpacity:a.V.Ao.backgroundOpacity;e=XPz(e);U.background="rgba("+e[0]+","+e[1]+","+e[2]+","+T+")";a.hN&&(U["box-decoration-break"]="clone",U["border-radius"]=a.fO/8+"px")}if(I.fontSizeIncrement!=null||I.offset!=null)U["font-size"]=a.a$*wPD(I)+"px";e=1;T=I.color||a.V.Ao.color;if(I.color||I.textOpacity!=null)T=XPz(T),e=I.textOpacity==null?a.V.Ao.textOpacity:I.textOpacity,T="rgba("+T[0]+","+T[1]+","+T[2]+","+e+")",
U.color=T,U.fill=T;var C=I.charEdgeStyle;C===0&&(C=void 0);if(C){T="rgba(34, 34, 34, "+e+")";var r="rgba(204, 204, 204, "+e+")";I.Xp&&(r=T=I.Xp);var q=a.a$/16/2,x=Math.max(q,1),Z=Math.max(2*q,1),t=Math.max(3*q,1),n=Math.max(5*q,1);e=[];switch(C){case 4:for(;t<=n;t+=q)e.push(Z+"px "+Z+"px "+t+"px "+T);break;case 1:Z=window.devicePixelRatio>=2?.5:1;for(C=x;C<=t;C+=Z)e.push(C+"px "+C+"px "+T);break;case 2:e.push(x+"px "+x+"px "+r);e.push("-"+x+"px -"+x+"px "+T);break;case 3:for(t=0;t<5;t++)e.push("0 0 "+
Z+"px "+T)}U["text-shadow"]=e.join(", ")}T="";switch(I.fontFamily){case 1:T='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:T='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:T='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:T='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:T='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:T=g.N6()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:T='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}T&&(U["font-family"]=T);T=I.offset;T==null&&(T=a.V.Ao.offset);switch(T){case 0:U["vertical-align"]="sub";break;case 2:U["vertical-align"]="super"}I.fontFamily===7&&(U["font-variant"]="small-caps");I.bold&&(U["font-weight"]="bold");I.italic&&(U["font-style"]="italic");I.underline&&(U["text-decoration"]=
"underline");I.qxX&&(U.visibility="hidden");I.YK===1&&a.B&&(U["text-combine-upright"]="all",U["text-orientation"]="mixed",T=g.rI||g.gz,a.L.params.mH===3?U.transform=T?"rotate(90deg)":"rotate(180deg)":T&&(U.transform="rotate(-90deg)"));if(I.textEmphasis===1||I.textEmphasis===2||I.textEmphasis===3||I.textEmphasis===4||I.textEmphasis===5)if(g.rI)U["font-weight"]="bold";else switch(U["text-emphasis-style"]="filled circle",U["text-emphasis-color"]="currentcolor",U["webkit-text-emphasis"]="filled circle",
I.textEmphasis){case 4:case 3:U["text-emphasis-position"]="under left";U["webkit-text-emphasis-position"]="under left";break;case 5:case 2:U["text-emphasis-position"]="over right",U["webkit-text-emphasis-position"]="over right"}return U},qp=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},ztI=function(a){a.D=g.vA("SPAN");
g.Gr(a.D,{display:"block"});g.x5(a.D,"caption-visual-line");a.J.appendChild(a.D)},htz=function(a,I){var U=g.vA("SPAN");
g.Gr(U,{display:"inline-block","white-space":"pre-wrap"});g.Gr(U,QW4(a,I));U.classList.add("ytp-caption-segment");a.D.appendChild(U);U.previousElementSibling&&(g.Gr(U.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Gr(U,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return U},Nbm=function(a,I,U){a.dw=a.dw||!!U;
var e={};Object.assign(e,a.V.Ao);Object.assign(e,U||I.V);Object.assign(e,a.IF.Ao);(U=!a.D)&&ztI(a);for(var T=a.Ux&&a.zt&&g.Ix(e,a.zt)?a.Ux:htz(a,e),C=typeof I.text==="string",r=C?I.text.split("\n"):[I.text],q=0;q<r.length;q++){var x=q>0||!I.append,Z=r[q];x&&!U?(ztI(a),T=htz(a,e)):x&&U&&(U=!1);Z&&(T.appendChild(C?g.aA(Z):Z),C||Z.tagName!=="RUBY"||Z.childElementCount!==4||g.rI||!g.dU(Z.children[2],"text-emphasis")||(x=a.B?"padding-right":"padding-top",g.dU(Z.children[2],"text-emphasis-position")&&(x=
a.B?"padding-left":"padding-bottom"),g.hl?g.Gr(T,x,"1em"):g.Gr(T,x,"0.5em")))}a.zt=e;a.Ux=T;a.C.push(I)},RtQ=function(a,I,U,e){var T=I/360*16;
I>=a&&(a=640,e>U*1.3&&(a=480),T=U/a*16);return T},DSd=function(){this.B=this.time=this.mode=this.L=0;
this.J=new oOI(this);this.U=new oOI(this);this.V=[];this.clear()},aZI=function(a,I,U){if(a===255&&I===255||!a&&!I)return{MH:a,
aO:I,result:0};a=vOJ[a];I=vOJ[I];if(a&128){var e;if(e=!(I&128))e=I,e=U.qJ()&&U.aO===e;if(e)return{MH:a,aO:I,result:1}}else if(I&128&&1<=a&&a<=31)return{MH:a,aO:I,result:2};return{MH:a,aO:I,result:3}},sDz=function(a,I,U,e){I===255&&U===255||!I&&!U?(++a.B===45&&a.reset(),a.J.L.clear(),a.U.L.clear()):(a.B=0,IZm(a.J,I,U,e))},U1d=function(a,I){a.V.sort(function(T,C){var r=T.time-C.time;
return r===0?T.order-C.order:r});
for(var U=g.k(a.V),e=U.next();!e.done;e=U.next())e=e.value,a.time=e.time,e.type===0?sDz(a,e.cC,e.EA,I):e.type===1&&a.L&496&&IZm(a.U,e.cC,e.EA,I);a.V.length=0},xC=function(){this.type=0},Zd=function(){this.state=this.aO=this.MH=0},ewo=function(){this.timestamp=this.V=0},tI=function(a){this.U=a;
this.B=[];this.V=this.L=this.row=0;this.style=new xC;for(a=this.J=0;a<=15;a++){this.B[a]=[];for(var I=0;I<=32;I++)this.B[a][I]=new ewo}},nL=function(a,I){if(a.style.type===3){for(var U=0,e=0,T=a.U.time+0,C="",r="",q=T,x=1;x<=15;++x){for(var Z=!1,t=e?e:1;t<=32;++t){var n=a.B[x][t];
if(n.V!==0){U===0&&(U=x,e=t);Z=String.fromCharCode(n.V);var K=n.timestamp;K<T&&(T=K);n.timestamp=q;r&&(C+=r,r="");C+=Z;Z=!0}if((n.V===0||t===32)&&Z){r="\n";break}else if(e&&!Z)break}if(U&&!Z)break}C&&I.J(U,e,T,q,C)}else for(e=U=0,C=T=a.U.time+0,r=1;r<=15;++r)for(q="",x=1;x<=32;++x)if(t=a.B[r][x],n=t.V,n!==0&&(U===0&&(U=r,e=x),Z=String.fromCharCode(n),K=t.timestamp,K<=T&&(T=K),q+=Z,t.reset()),x===32||n===0)q&&I.J(U,e,T,C,q),T=C,q="",e=U=0},q8f=function(a,I){switch(a){case 0:return TU8[(I&127)-32];
case 1:return Cp4[I&15];case 2:return rOQ[I&31];case 3:return Hzz[I&31]}return 0},KL=function(a){return a.B[a.row][a.L]},bx=function(a,I,U){I>=2&&a.L>1&&(--a.L,KL(a).V=0);
var e=KL(a);e.timestamp=a.U.time+0;e.V=q8f(I,U);a.L<32&&a.L++},x18=function(a,I,U,e){for(var T=0;T<e;T++)for(var C=0;C<=32;C++){var r=a.B[I+T][C],q=a.B[U+T][C];
r.V=q.V;r.timestamp=q.timestamp}},JI=function(a,I,U){for(var e=0;e<U;e++)for(var T=0;T<=32;T++)a.B[I+e][T].reset()},Zzd=function(a){a.row=a.V>0?a.V:1;
a.L=1;JI(a,0,15)},t2Q=function(a){this.B=a;
this.U=0;this.style=new xC;this.Y=new tI(this.B);this.C=new tI(this.B);this.text=new tI(this.B);this.L=this.Y;this.J=this.C;this.V=this.L},nfI=function(a,I,U){var e=a.L,T=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&e.V>0||(nL(e,U),Zzd(a.L),Zzd(a.J),e.row=15,e.V=I,T=!0)}a.style.set(3);a.V=e;a.V.style=a.style;a.B.mode=1<<e.J;T?e.L=1:e.V!==I&&(e.V>I?(nL(e,U),JI(e,e.row-e.V,I)):e.row<I&&(I=e.V),e.V=I)},KLo=function(a){a.style.set(1);
a.V=a.J;a.V.V=0;a.V.style=a.style;a.B.mode=1<<a.V.J},bzo=function(a){a.style.set(4);
a.V=a.text;a.V.style=a.style;a.B.mode=1<<a.V.J},oOI=function(a){this.V=a;
this.U=0;this.B=new t2Q(this.V);this.Y=new t2Q(this.V);this.L=new Zd;this.J=this.B},IZm=function(a,I,U,e){a.L.update();
I=aZI(I,U,a.L);switch(I.result){case 0:return;case 1:case 2:return}var T=I.MH;U=I.aO;if(32<=T||!T)a.V.mode&a.V.L&&(I=T,I&128&&(I=127),U&128&&(U=127),a=a.J.V,I&96&&bx(a,0,I),U&96&&bx(a,0,U),I!==0&&U!==0&&a.style.type===3&&nL(a,e));else if(T&16)a:if(!a.L.matches(T,U)&&(I=a.L,I.MH=T,I.aO=U,I.state=2,I=T&8?a.Y:a.B,a.J=I,a.V.mode=1<<(a.U<<2)+(I.U<<1)+(I.style.type===4?1:0),(a.V.mode|1<<(a.U<<2)+(I.U<<1)+(I.style.type!==4?1:0))&a.V.L))if(U&64){e=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(T&7)<<1|U>>5&1];
a=U&16?((U&14)>>1)*4:0;U=I.V;switch(I.style.get()){case 4:e=U.row;break;case 3:if(e!==U.row){if(e<U.V&&(e=U.V,e===U.row))break;var C=1+U.row-U.V,r=1+e-U.V;x18(U,r,C,U.V);I=C;T=U.V;r<C?(C=r+T-C,C>0&&(I+=C,T-=C)):(C=C+T-r,C>0&&(T-=C));JI(U,I,T)}}U.row=e;U.L=a+1}else switch(T&7){case 1:switch(U&112){case 32:bx(I.V,0,32);break a;case 48:U===57?(e=I.V,KL(e).V=0,e.L<32&&e.L++):bx(I.V,1,U&15)}break;case 2:U&32&&bx(I.V,2,U&31);break;case 3:U&32&&bx(I.V,3,U&31);break;case 4:case 5:if(32<=U&&U<=47)switch(U){case 32:KLo(I);
break;case 33:e=I.V;e.L>1&&(--e.L,KL(e).V=0);break;case 36:e=I.V;I=KL(e);for(a=0;a<=15;a++)for(U=0;U<=32;U++)if(e.B[a][U]===I){for(;U<=32;U++)e.B[a][U].reset();break}break;case 37:nfI(I,2,e);break;case 38:nfI(I,3,e);break;case 39:nfI(I,4,e);break;case 40:bx(I.V,0,32);break;case 41:I.style.set(2);I.V=I.L;I.V.V=0;I.V.style=I.style;I.B.mode=1<<I.V.J;break;case 42:e=I.text;e.V=15;e.style.set(4);Zzd(e);bzo(I);break;case 43:bzo(I);break;case 44:a=I.L;switch(I.style.get()){case 1:case 2:case 3:nL(a,e)}JI(a,
0,15);break;case 45:b:{a=I.V;switch(I.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.L=1;break b}break;case 3:}a.V<2&&(a.V=2,a.row<a.V&&(a.row=a.V));I=a.row-a.V+1;nL(a,e);x18(a,I,I+1,a.V-1);JI(a,a.row,1)}break;case 46:JI(I.J,0,15);break;case 47:nL(I.L,e),I.J.updateTime(I.B.time+0),e=I.J,I.J=I.L,I.L=e,KLo(I)}break;case 7:switch(U){case 33:case 34:case 35:e=I.V,(e.L+=U&3)>32&&(e.L=32)}}},JOj=function(){},ux=function(a,I,U,e,T,C,r){C=C===void 0?!1:C;
r=r===void 0?null:r;g.qA.call(this,a,a+I,{priority:U,namespace:"captions"});this.windowId=e;this.text=T;this.append=C;this.V=r},kro=function(a,I,U,e,T,C,r){var q=C[0],x=r[g.O(q.getAttribute("p"))];
if(x.U1===1){var Z=C[1],t=C[2];C=C[3];q.getAttribute("t");Z.getAttribute("t");t.getAttribute("t");C.getAttribute("t");q.getAttribute("p");Z.getAttribute("p");C.getAttribute("p");r=r[g.O(t.getAttribute("p"))];q=u7o(q.textContent,Z.textContent,t.textContent,C.textContent,r);return new ux(a,I,T,U,q,e,x)}switch(x.U1){case 9:case 10:x.textEmphasis=1;break;case 11:x.textEmphasis=2;break;case 12:x.textEmphasis=3;break;case 13:x.textEmphasis=4;break;case 14:x.textEmphasis=5}return new ux(a,I,T,U,q.textContent||
"",e,x)},u7o=function(a,I,U,e,T){var C=g.N6(),r=C?g.vA("DIV"):g.vA("RUBY"),q=g.vA("SPAN");
q.textContent=a;r.appendChild(q);a=C?g.vA("DIV"):g.vA("RP");a.textContent=I;r.appendChild(a);I=C?g.vA("DIV"):g.vA("RT");I.textContent=U;r.appendChild(I);U=T.U1;if(U===10||U===11||U===12||U===13||U===14)if(g.Gr(I,"text-emphasis-style","filled circle"),g.Gr(I,"text-emphasis-color","currentcolor"),g.Gr(I,"webkit-text-emphasis","filled circle"),T.U1===11||T.U1===13)g.Gr(I,"webkit-text-emphasis-position","under left"),g.Gr(I,"text-emphasis-position","under left");U=!0;if(T.U1===4||T.U1===7||T.U1===12||
T.U1===14)g.Gr(r,"ruby-position","over"),g.Gr(r,"-webkit-ruby-position","before");else if(T.U1===5||T.U1===6||T.U1===11||T.U1===13)g.Gr(r,"ruby-position","under"),g.Gr(r,"-webkit-ruby-position","after"),U=!1;T=C?g.vA("DIV"):g.vA("RP");T.textContent=e;r.appendChild(T);C&&(e=U,g.Gr(r,{display:"inline-block",position:"relative"}),C=r.firstElementChild.nextElementSibling,g.Gr(C,"display","none"),C=C.nextElementSibling,g.Gr(C,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Gr(r.lastElementChild,"display","none"),e?(g.Gr(r,"padding-top","0.6em"),g.Gr(C,"top","0")):(g.Gr(r,"padding-bottom","0.6em"),g.Gr(C,"bottom","0")));return r},kC=function(){g.S.apply(this,arguments)},V4=function(a,I,U,e,T){g.qA.call(this,a,a+I,{priority:U,
namespace:"captions"});this.id=e;this.params=T;this.V=[]},V2I=function(a){var I="_"+AI++;
return new V4(0,0x8000000000000,0,I,a)},Mp=function(a){kC.call(this);
this.B=a;this.pens={};this.C={};this.D={};this.J="_"+AI++;this.Y={};this.L=this.V=null;this.U=!0},jl=function(a,I){a=a.getAttribute(I);
if(a!=null)return Number(a)},$C=function(a,I){a=a.getAttribute(I);
if(a!=null)return a==="1"},ix=function(a,I){a=jl(a,I);
return a!==void 0?a:null},gQ=function(a,I){a=a.getAttribute(I);
if(a!=null)return LL.test(a),a},AO4=function(a,I){var U={},e=I.getAttribute("ws");
Object.assign(U,e?a.D[e]:a.B);a=ix(I,"mh");a!=null&&(U.N0=a);a=ix(I,"ju");a!=null&&(U.textAlign=a);a=ix(I,"pd");a!=null&&(U.mH=a);a=ix(I,"sd");a!=null&&(U.Mi=a);a=gQ(I,"wfc");a!=null&&(U.windowColor=a);I=jl(I,"wfo");I!==void 0&&(U.windowOpacity=I/255);return U},M2z=function(a,I){var U={},e=I.getAttribute("wp");
e&&Object.assign(U,a.C[e]);a=ix(I,"ap");a!=null&&(U.Tw=a);a=jl(I,"cc");a!=null&&(U.QO=a);a=jl(I,"ah");a!=null&&(U.Sl=a);a=jl(I,"rc");a!=null&&(U.iG=a);I=jl(I,"av");I!=null&&(U.Z4=I);return U},jDJ=function(a,I,U,e){var T={};
Object.assign(T,M2z(a,I));Object.assign(T,AO4(a,I));e?g.Ix(T,a.B)?(e=a.J,T=a.B):e="_"+AI++:e=I.getAttribute("id")||"_"+AI++;a=jl(I,"t")+U;I=jl(I,"d")||0x8000000000000;if(T.mH===2||T.mH===3)U=T.iG,T.iG=T.QO,T.QO=U;return new V4(a,I,0,e,T)},cs=function(a){kC.call(this);
this.U=a;this.V=new Map;this.B=new Map;this.J=new Map;this.L=new Map},Ws=function(a){a=g.WA(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-a.length)+a},$1f=function(a,I,U,e,T){e===0&&(e=0x8000000000000);
var C={};I.wpWinPosId&&Object.assign(C,g.O(a.B.get(I.wpWinPosId)));I.wsWinStyleId&&Object.assign(C,g.O(a.J.get(I.wsWinStyleId)));a=I.rcRowCount;a!==void 0&&(C.iG=a);I=I.ccColCount;I!==void 0&&(C.QO=I);if(C.mH===2||C.mH===3)I=C.iG,C.iG=C.QO,C.QO=I;return new V4(U,e,0,T,C)},lx=function(a,I,U){g.bD.call(this,a);
this.videoData=I;this.audioTrack=U;this.U=I.eL},Bs=function(a,I,U,e,T,C,r,q,x,Z){Hs.call(this,a,I,U,e,T,C,r,q,x,Z);
this.type=1},Xt=function(a,I,U){this.trackData=a;
this.Y=U;this.version=this.U=this.B=this.byteOffset=0;this.L=[];this.V=new DataView(this.trackData)},Ps=function(a){var I=a.byteOffset;
a.byteOffset+=1;return a.V.getUint8(I)},pL=function(a){var I=a.byteOffset;
a.byteOffset+=4;return a.V.getUint32(I)},fL=function(a,I){kC.call(this);
this.L=a;this.B=I;this.track=this.B.languageName==="CC3"?4:0;this.V=new DSd;this.V.L=1<<this.track},LLJ=function(a){if(typeof a==="string")return!1;
a=new Xt(a,8,0);return izz(a)},izz=function(a){if(!(a.byteOffset<a.V.byteLength)||pL(a)!==1380139777)return!1;
a.version=Ps(a);if(a.version>1)return!1;Ps(a);Ps(a);Ps(a);return!0},YC=function(a,I,U,e,T,C,r,q,x,Z){Hs.call(this,a,I,U,e,T,C,r,q,x,Z);
var t=this;this.type=2;this.e8=[];this.Va=this.j=this.CO=0;this.tU=NaN;this.Vo=0;this.rF=null;this.B8=new g.Dy(this.f_,433,this);this.Y&&(Z.createClientVe(this.Y,this,167342),this.G(this.Y,"click",function(){Z.logClick(t.Y)}),a=new g.O9(this.element,!0),g.E(this,a),a.subscribe("hoverstart",function(){Z.logVisibility(t.Y,!0)},this));
g.x5(this.element,"ytp-caption-window-rollup");g.E(this,this.B8);g.Gr(this.element,"overflow","hidden")},gfo=function(a,I){if(!I)return"";
a.B&&a.L.params.Mi!==1&&(I*=-1);return"translate"+(a.B?"X":"Y")+"("+I+"px)"},cOj=function(a){a.e8=Array.from(a.element.getElementsByClassName("caption-visual-line"));
for(var I=a.L.params.iG,U=0,e=0,T=a.e8.length-1;U<I&&T>-1;){var C=a.e8[T];e+=a.B?C.offsetWidth:C.offsetHeight;U++;T--}a.j=e;I=Math;U=I.max;isNaN(a.tU)&&((e=a.V.QO)?(T=g.vA("SPAN"),g.CM(T,"\u2013".repeat(e)),g.Gr(T,QW4(a,a.V.Ao)),a.J.appendChild(T),a.tU=T.offsetWidth,a.J.removeChild(T)):a.tU=0);e=a.J;a.Va=U.call(I,a.tU,a.Vo,(a.B?e.offsetHeight:e.offsetWidth)+1)},WLd=function(a,I){cOj(a);
var U=a.e8.reduce(function(C,r){return(a.B?r.offsetWidth:r.offsetHeight)+C},0);
U=a.j-U;if(U!==a.CO){var e=U>0&&a.CO===0,T=U<a.CO;I||isNaN(U)||e||!T||(g.x5(a.element,"ytp-rollup-mode"),a.G(a.element,"transitionend",a.f_));g.Gr(a.J,"transform",gfo(a,U));a.CO=U}cOj(a)},lZz=function(a,I,U,e){var T=this;
this.K=a;this.B=I;this.logger=U;this.U7=e;this.P8=[];this.sS=[];this.V=null;this.Ah={pkX:function(){return T.V},
gV:function(){return T.P8}};
a=g.ki(this.K.X().experiments,"html5_override_micro_discontinuities_threshold_ms");this.L=a>0?a:10},PpD=function(a,I){a.V=function(U,e){if(U.info.U){var T=U;
if(a.sS.length>0){for(T=a.sS.shift();a.sS.length>0;)T=g.n8(T,a.sS.shift());T=g.n8(T,U)}if(T){U=T;try{var C=g.K8(U)*1E3}catch(Z){C=U.info.startTime*1E3}try{var r=g.P2c(U)*1E3}catch(Z){r=U.info.duration*1E3}if(C<0||r<0)C<0&&(C=U.info.startTime*1E3),r<0&&(r=U.info.duration*1E3);U.info.startTime=C/1E3;U.info.J=C/1E3;U.info.duration=r/1E3;U.info.D=r/1E3;C=a.yv(T);r=C.pO;C={formatId:C.formatId,startTimeMs:C.startTimeMs,durationMs:C.durationMs,Ai:r,R1:r};r=BUd(a.P8,C.startTimeMs);var q=(U=r>=0?a.P8[r]:null)?
U.startTimeMs+U.durationMs:0,x=C.startTimeMs+C.durationMs;!U||C.startTimeMs-q>a.L?a.P8.splice(r+1,0,C):(U.durationMs=Math.max(q,x)-U.startTimeMs,U.R1=Math.max(U.R1,C.R1));e(a.P8);e=T.t4();Xaz(a.B,e.buffer.slice(e.byteOffset,e.byteLength+e.byteOffset),I,T.info.J)}else a.logger.V(350058965,"Empty slice")}else a.sS.push(U)};
a.K.addEventListener("sabrCaptionsDataLoaded",a.V)},BUd=function(a,I){a=g.Po(a,{startTimeMs:I},function(U,e){return U.startTimeMs-e.startTimeMs});
return a>=0?a:-a-2},pa4=function(a,I){g.bD.call(this,I);
this.V=a;this.K=I;this.logger=new g.bh("caps");this.B=this.Y=null;this.C=new lZz(this.K,this,this.logger,this.V.U7)},Xaz=function(a,I,U,e){a.logger.debug(function(){return"SABR captions data received for "+e});
a.Y?a.B==null?a.logger.V(350058965,"Null loaded track meta data at captions data received"):U.xz(I,a.B,e*1E3):a.logger.V(350058965,"Null Representation at captions data received")},fZm=function(a,I){var U=[],e;
for(e in a.V.V)if(a.V.V.hasOwnProperty(e)){var T=a.V.V[e];if(g.uD(T,I||null)){var C=T.info.id,r=C,q="."+C,x="",Z="";if(T=T.info.captionTrack)C=T.languageCode,r=T.displayName,q=T.vssId,x=T.kind,Z=T.id;U.push(new g.Mh({id:e,languageCode:C,languageName:r,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:q,kind:x,captionId:Z}))}}return U},Y8J=function(a,I,U){var e=[],T;
for(T in a.V.V)if(a.V.V.hasOwnProperty(T)){var C=a.V.V[T];if(g.uD(C,U||null)){var r=C.info.captionTrack;r&&r.languageCode===I&&e.push(C)}}return e.length?e[0]:null},Ozz=function(a,I){if(!g.JCY(a)||a.V!=null&&g.Bj(I.X())&&!a.V.isManifestless&&a.V.V.rawcc!=null)return!1;
I=!!a.V&&a.V.isManifestless&&Object.values(a.V.V).some(function(U){return g.uD(U,"386")});
a=!!a.V&&!a.V.isManifestless&&g.Q_i(a.V);return I||a},Oo=function(){kC.call(this)},GrD=function(a){var I=S8d.length;
if(a.byteLength<I)return!1;a=new Uint8Array(a,0,I);for(var U=0;U<I;U++)if(S8d[U]!==a[U])return!1;return!0},yOo=function(a,I,U,e,T,C,r,q,x){switch(r.tagName){case "b":q.bold=!0;
break;case "i":q.italic=!0;break;case "u":q.underline=!0}for(var Z=0;Z<r.childNodes.length;Z++){var t=r.childNodes[Z];if(t.nodeType===3)t=new ux(I,U,e,T.id,t.nodeValue,C||Z>0,g.vo(q)?void 0:q),x.push(t),T.V.push(t);else{var n={};Object.assign(n,q);yOo(a,I,U,e,T,!0,t,n,x)}}},Efj=function(a){var I=a.split(":");
a=0;I=g.k(I);for(var U=I.next();!U.done;U=I.next())a=a*60+Number(U.value);return a*1E3},d1J=function(a,I,U,e){e=Object.assign({N0:0},e);
return new V4(a,I,U,"_"+AI++,e)},Sl=function(a,I){g.S.call(this);
this.K=a;this.Ex=I;this.V=null;this.L=this.K.g3();this.logger=new g.bh("caps")},waz=function(a,I,U){if(typeof I==="string"||LLJ(I))return[{trackData:I,
Hm:U}];if(typeof I==="string"&&I.substring(0,6)==="WEBVTT"||typeof I!=="string"&&GrD(I))return[{trackData:I,Hm:U}];var e=new DataView(I);if(e.byteLength<=8||e.getUint32(4)!==1718909296)return[];var T=g.ygS(e);if(a.L&&T){var C=g.XdI(T),r=g.PTF(T);T=T.ML;C&&T&&a.L.qT(T,C,r)}a=g.n2(e,1835295092);if(!a||!a.length||!a[0].size)return[];C=[];for(r=0;r<a.length;r++)T=a[r],T=new Uint8Array(I,T.dataOffset,T.size-(T.dataOffset-T.offset)),T=g.pU(T),C.push({trackData:T,Hm:U+r*1E3});Rwd(e,C,U);return C=C.filter(function(q){return!!q.trackData})},
Rwd=function(a,I,U){var e=g.ej(a,0,1836476516),T=9E4;
e&&(T=g.TS(e)||9E4);e=0;for(var C=g.n2(a,1836019558),r=0;r<C.length;r++){var q=C[r];r<I.length&&(q=g.ej(a,q.dataOffset,1953653094))&&(q=g.ej(a,q.dataOffset,1952867444))&&(q=g.Zt(q)/T*1E3,r===0&&(e=q),I[r].Hm=q-e+U||U*r*1E3)}},FL8=function(a,I,U){a.V||(a.V=new Oo);
a=a.V.Mm(I,U);Math.random()<.01&&g.RS(Error("Deprecated subtitles format in web player: WebVTT"));return a},m18=function(a){var I={};
if(a=g.iq(a))I.lang=a,g.Prz.test(a)&&(I.mH=1);return I},GN=function(a){g.nu.call(this,a);
var I=this;this.K=a;this.Ux=[];this.e8={};this.fO={};this.D=!1;this.J="NONE";this.V=this.j=this.Va=this.a$=this.i5=null;this.hN={F9:function(){I.F9()},
xz:function(C,r,q,x){I.xz(C,r,q,x)}};
this.L=null;this.Ex=this.K.X();this.videoData=g.O(this.K.getVideoData());this.E7=this.K.j8();var U;this.xa=(U=this.K.getVideoData(1))==null?void 0:g.sc(U);this.B={Ao:{}};this.Y={Ao:{}};g.I4(this.videoData)?this.J="OFFLINE":Ozz(this.videoData,this.K)?this.J="SABR_LIVE":g.Anq(this.videoData,this.K)?this.J="LIVE":this.videoData.captionTracks.length?this.J="INNERTUBE":this.videoData.q2&&(this.J="TTS");this.Z6=this.Ex.controlsType==="3";this.XX=new Sl(this.K,this.Ex);this.tU=new g.Ru(this);this.C=new g.F({W:"div",
T:"ytp-caption-window-container",S:{id:"ytp-caption-window-container"}});this.gw={top:0,right:0,bottom:0,left:0,width:1,height:1};U=null;var e=g.Eb("yt-html5-player-modules::subtitlesModuleData");e&&(U=new g.Xz(e));this.storage=U;var T;this.Vo=!((T=a.K4())==null||!T.bD());this.U=QDz(this);this.dw=!this.U&&this.Z6&&this.Vo&&(this.J==="LIVE"||this.J==="SABR_LIVE");g.E(this,this.XX);this.U?this.CO=this.zt=null:(this.zt=new g.oj(this.Sg,void 0,this),g.E(this,this.zt),this.CO=new g.Dy(this.XZg,2E3,this),
g.E(this,this.CO));g.E(this,this.tU);g.w4(this.player,this.C.element,4);g.E(this,this.C);this.U||this.tU.G(a,"resize",this.mI);(this.B8=g.EZ(this.Ex)&&!g.jR()&&!this.K.isFullscreen()&&!this.U&&!this.dw)&&this.tU.G(a,"resize",this.mDX);this.tU.G(a,"onPlaybackAudioChange",this.kCg);this.tU.G(a,g.ZW("captions"),function(C){I.onCueRangeEnter(C)});
this.tU.G(a,g.tS("captions"),function(C){I.onCueRangeExit(C)});
this.xa&&this.tU.G(a,"videodatachange",function(C,r){I.onVideoDataChange(C,r)});
zw4(this,pPG()||{});this.player.s9("onCaptionsModuleAvailable")},ofz=function(a){if(a.Ex.Vo===1||a.videoData.t7===1||g.l8(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var I=a.getAudioTrack().L;if(a.Ex.Vo===2){if(g.eI(a.Ex))var U=hwj(a);else if(a.storage)try{U=a.storage.get("module-enabled")}catch(T){a.storage.remove("module-enabled")}else U=null;if(U!=null)return!!U}U=iXz(a.player.getAudioTrack(),g.eI(a.Ex));var e=g.l8(a.videoData,"yt:cc");if(NU8(a)===void 0){if(U==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return e?e==="on":!0;if(U==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return e==="on"}else return e==="on";return I==="ON"||
g.l8(a.videoData,"yt:cc")==="on"},y4=function(a,I){if(a.L&&(I===void 0||!I)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.V||a.L==="FORCED_ON"},NU8=function(a){var I=void 0,U=g.z8(g.Qy(),65);
if(g.eI(a.Ex)&&U!=null){if(hwj(a)!=null)return!1;I=!U}return I},dQ=function(a,I){if(!a.V)return null;
if(a.j&&a.j.J)return a.j.J;I=D1o(a,I);I=g.aP(a.V.L,I);var U=null;if(L5z(a.Ex)){var e=a.K.isInline()?void 0:g.EV("yt-player-caption-sticky-language");for(var T=[e,a.videoData.captionsLanguagePreference,a.Ex.captionsLanguagePreference,g.l8(a.videoData,"yt:cc_default_lang")],C=!1,r=0;r<T.length;r++){var q=T[r];if(q){C=!0;for(var x=0;x<I.length;x++)if(g.iq(I[x])===q)return I[x];for(x=0;x<I.length;x++)if(g.iq(I[x]).split("-")[0]===q.split("-")[0])return I[x]}}if(C&&a.V&&(T=a.V.U,T.length))for(T=g.k(T),
C=T.next();!C.done;C=T.next())if(C=C.value,C.languageCode===e){U=C;break}}else for(e=[a.videoData.captionsLanguagePreference,a.Ex.captionsLanguagePreference,g.l8(a.videoData,"yt:cc_default_lang")],T=0;T<e.length;T++)for(C=0;C<I.length;C++)if(g.iq(I[C])===e[T])return I[C];e=null;a.j&&a.j.B&&(e=a.j.B);e||(e=I.find(function(Z){return Z.isDefault})||null);
e||(e=I[0]||Eo(a));e&&U&&g.iq(e).split("-")[0]!==U.languageCode.split("-")[0]&&(e=gOf(e,U));return e},Eo=function(a){return a.j&&a.j.V},Rz=function(a){var I=Eo(a);
return!!I&&a.L===I},vfo=function(a,I){var U=g.O(a.K.K4().oF()).textTracks;
a=a.L.toString();for(var e=0;e<U.length;e++){var T=U[e];T.id===a&&(I?T.mode!=="showing"&&(T.mode="showing"):T.mode==="showing"&&(T.mode="disabled"))}},mc=function(a,I,U){a.loaded&&a.unload();
U!=null&&(a.D=U,a.D&&(g.eI(a.Ex)?wQ(a,!!I):Ft(a,!!I)));akd(a,a.L,I,a.D,!1);a.L=I;y4(a)&&(I=Eo(a),akd(a,a.L,I,a.D,!0),a.L=I);var e;IkJ(a,(e=a.L)!=null?e:void 0);a.load()},Ufo=function(a,I){if(I instanceof V4){var U=a.e8[I.id];
U&&U.L!==I&&(U.dispose(),delete a.e8[I.id],U=null);U||(U=sR8(a,I))&&(a.e8[I.id]=U)}else U=I.windowId,a.fO[U]||(a.fO[U]=[]),a.fO[U].push(I)},sR8=function(a,I){var U=ePd(a);
if(!U)return null;var e=a.L?g.iq(a.L):null;e&&g.Prz.test(e)&&(I.params.mH=1);var T=a.E7.getPlayerSize();e=T.height*a.gw.height;T=T.width*a.gw.width;a.Ex.playerStyle!=="google-live"||a.B.isDefault||Object.assign(I.params,a.B);switch(I.params.N0!=null?I.params.N0:I.V.length>1?1:0){case 1:return new Bs(I,a.B,a.Y,U.width,U.height,T,e,a.Ex.experiments,a.Uc.bind(a),a.K);case 2:return new YC(I,a.B,a.Y,U.width,U.height,T,e,a.Ex.experiments,a.Uc.bind(a),a.K);default:return new Hs(I,a.B,a.Y,U.width,U.height,
T,e,a.Ex.experiments,a.Uc.bind(a),a.K)}},zw4=function(a,I,U){U=U===void 0?!1:U;
var e=Q4.Ao;a.B={};Object.assign(a.B,Q4);a.B.Ao={};Object.assign(a.B.Ao,e);a.Y={Ao:{}};var T=I.backgroundOverride?a.Y:a.B,C=I.background||e.background;LL.test(C);T.Ao.background=C;T=I.colorOverride?a.Y:a.B;C=I.color||e.color;LL.test(C);T.Ao.color=C;T=I.windowColorOverride?a.Y:a.B;C=I.windowColor||Q4.windowColor;LL.test(C);T.windowColor=C;T=I.backgroundOpacityOverride?a.Y:a.B;C=I.backgroundOpacity;C==null&&(C=e.backgroundOpacity);T.Ao.backgroundOpacity=C;T=I.fontSizeIncrementOverride?a.Y:a.B;C=I.fontSizeIncrement;
C==null&&(C=e.fontSizeIncrement);T.Ao.fontSizeIncrement=C;C=I.fontStyleOverride?a.Y:a.B;T=I.fontStyle;T==null&&(T=e.bold&&e.italic?3:e.bold?1:e.italic?2:0);C=C.Ao;switch(T){case 1:C.bold=!0;delete C.italic;break;case 2:delete C.bold;C.italic=!0;break;case 3:C.bold=!0;C.italic=!0;break;default:delete C.bold,delete C.italic}T=I.textOpacityOverride?a.Y:a.B;C=I.textOpacity;C==null&&(C=e.textOpacity);T.Ao.textOpacity=C;T=I.windowOpacityOverride?a.Y:a.B;C=I.windowOpacity;C==null&&(C=Q4.windowOpacity);T.windowOpacity=
C;T=I.charEdgeStyleOverride?a.Y:a.B;C=I.charEdgeStyle;C==null&&(C=e.charEdgeStyle);T.Ao.charEdgeStyle=C;T=I.fontFamilyOverride?a.Y:a.B;C=I.fontFamily;C==null&&(C=e.fontFamily);T.Ao.fontFamily=C;a.loaded&&a.mI();U&&g.yy("yt-player-caption-display-settings",I,2592E3)},Tem=function(a,I){if(!a.V)return{};
if(I){g.vo(I)||a.cX(I.vss_id,"m");if(a.U||!g.If(I))return;if(g.vo(I)){mc(a,null,!0);return}for(var U,e=g.aP(a.V.L,!0),T=0;T<e.length;T++){var C=e[T];C.languageCode!==I.languageCode||U&&(C.languageName!==I.languageName||(C.captionId||"")!==(I.captionId||"")||g.jI(C)!==I.displayName)||(U=I.translationLanguage?gOf(C,I.translationLanguage):C)}a.Ec(I.position);!U||U===a.L&&a.loaded||(I=g.sN(),e=g.iq(U),I.length&&e===I[I.length-1]||(I.push(e),g.yy("yt-player-caption-language-preferences",I)),L5z(a.Ex)&&
!a.K.isInline()&&g.yy("yt-player-caption-sticky-language",e,2592E3),mc(a,U,!0))}else return a.loaded&&a.L&&!Rz(a)?g.$l(a.L):{};return""},rez=function(a,I,U){I&&!a.Va?(I=V2I({mH:0,
lang:"en"}),a.Va=[I,new ux(I.start,I.end-I.start,0,I.id,U!=null?U:"Captions look like this")],a.player.xw(a.Va)):!I&&a.Va&&(CHQ(a,a.Va),a.Va=null)},CHQ=function(a,I){a.player.L1(I);
I=g.k(I);for(var U=I.next();!U.done;U=I.next())g.Az(a.Ux,U.value);TN(a.zt)},IkJ=function(a,I){a.Ex.N("html5_modify_caption_vss_logging")&&(a.videoData.tE=I)},ePd=function(a){var I=a.E7.getVideoContentRect(!0).height,U=a.E7.getVideoContentRect(!0).width;
if(!I||!U)return null;I*=a.gw.height;U*=a.gw.width;return{width:U,height:I}},Ft=function(a,I){if(a.storage)try{a.storage.set("module-enabled",I)}catch(U){}},wQ=function(a,I){a.K.isInline()||g.yy("yt-player-sticky-caption",I,2592E3)},hwj=function(a){if(!a.K.isInline())return g.EV("yt-player-sticky-caption")},QDz=function(a){if(a.Ex.N("safari_live_drm_captions_fix")&&a.videoData.lN()&&a.videoData.U7()&&g.gz)return!0;
var I,U=!((I=a.K.K4())==null||!I.wQ());return a.Z6&&U&&a.J!=="LIVE"&&a.J!=="SABR_LIVE"},D1o=function(a,I){g.wN(a.videoData)&&(I=!0);
I||(I=a.J==="TTS"?!1:a.J==="INNERTUBE"?!1:!0);return I||a.Ex.N("web_deprecate_always_includes_asr_setting")&&g.eI(a.Ex)?!0:!!g.z8(g.Qy(),66)},akd=function(a,I,U,e,T){T?a.hS(U,!0,"g"):e?I?a.hS(U,!!U,"m"):U&&a.hS(U,!0,"m"):!I&&U&&a.hS(U,!0,"s")};
g.bD.prototype.hP=g.Cc(77,function(){return!1});
g.bD.prototype.MO=g.Cc(76,function(){});
g.Jh.prototype.MO=g.Cc(75,function(a,I,U){var e=this;this.Ox();I=this.BI(a,I);var T=this.Gt.X().N("html5_report_captions_ctmp_qoe"),C=(0,g.w)();this.S6();$Sf(this,I,{format:"RAW",onSuccess:function(r){e.V=null;if(T){var q=(r.responseText.length/1024).toFixed(),x=(0,g.w)();e.videoData.R$("capresp",{ms:x-C,kb:q})}U.xz(r.responseText,a)},
onError:T?function(r){var q;r=(q=r==null?void 0:r.status)!=null?q:0;e.videoData.R$("capfail",{status:r})}:void 0,
withCredentials:!0})});
g.kW.prototype.MO=g.Cc(74,function(a,I,U){var e=this;this.Ox();I=this.BI(a,I);this.S6();this.V=g.lk(I,{format:"RAW",onSuccess:function(T){e.V=null;U.xz(T.responseText,a)},
withCredentials:!0})});
g.Fc.prototype.Z1=g.Cc(73,function(){for(var a=g.mO(document,"track",void 0,this.V),I=0;I<a.length;I++)g.ec(a[I])});
g.la.prototype.Z1=g.Cc(72,function(){this.mediaElement.Z1()});
g.Fc.prototype.bD=g.Cc(71,function(){return!(!this.V.textTracks||!this.V.textTracks.addEventListener)});
g.la.prototype.bD=g.Cc(70,function(){return this.mediaElement.bD()});
g.Fc.prototype.wQ=g.Cc(69,function(){return!!this.V.textTracks});
g.la.prototype.wQ=g.Cc(68,function(){return this.mediaElement.wQ()});
g.Fc.prototype.M5=g.Cc(67,function(a){for(var I=0;I<a.length;I++)this.V.appendChild(a[I])});
g.la.prototype.M5=g.Cc(66,function(a){this.mediaElement.M5(a)});
g.Wy.prototype.qT=g.Cc(65,function(a,I,U){this.fv.qT(a,I,U)});
g.El.prototype.qT=g.Cc(64,function(a,I,U){this.L.set(a,{ZF:I,Nu:U})});
g.dF.prototype.qT=g.Cc(63,function(a,I,U){this.zt.qT(a,I,U)});
g.Wy.prototype.a7=g.Cc(62,function(a){return this.fv.a7(a)});
g.dF.prototype.a7=g.Cc(61,function(a){var I=2;this.j.has(a)?I=0:g.eIc(this,a)&&(I=1);return I});
g.Y8.prototype.Cr=g.Cc(49,function(a){var I=this.app.u5();return I?I.Cr(a):!1});
g.NC.prototype.Cr=g.Cc(48,function(a){return this.sx.AI.Cr(a)});
g.PR.prototype.Cr=g.Cc(47,function(a){return this.hI().some(function(I){return I.namespace===a})});
g.fS.prototype.Cr=g.Cc(46,function(){return!1});
g.Y8.prototype.cX=g.Cc(44,function(a,I){this.app.D6().cX(a,I)});
g.NC.prototype.cX=g.Cc(43,function(a,I){this.sx.cX(a,I)});
g.tB.prototype.cX=g.Cc(42,function(a,I){a=[a,I];g.Z3(this,g.cy(this.provider),"cfi",a)});
g.WR.prototype.cX=g.Cc(41,function(a,I){this.qoe&&this.qoe.cX(a,I)});
g.s9.prototype.cX=g.Cc(40,function(a,I){this.Qo().cX(a,I)});
g.fS.prototype.cX=g.Cc(39,function(){});
g.Y8.prototype.hS=g.Cc(38,function(a,I,U){this.app.D6().hS(a,I,U)});
g.NC.prototype.hS=g.Cc(37,function(a,I,U){this.sx.hS(a,I,U)});
g.tB.prototype.hS=g.Cc(36,function(a,I,U){if(this.CO!==a||this.IF!==I)I=I==="rawcc"?"":I,U=[a,I,this.CO,U],g.Z3(this,g.cy(this.provider),"cfs",U),this.CO=a,this.IF=I});
g.WR.prototype.hS=g.Cc(35,function(a,I,U){this.qoe&&this.qoe.hS(a,I,U)});
g.s9.prototype.hS=g.Cc(34,function(a,I,U){this.Qo().hS(a,I,U)});
g.fS.prototype.hS=g.Cc(33,function(){});
g.L3.prototype.md=g.Cc(20,function(){return this.Va});
g.K7.prototype.md=g.Cc(19,function(){return this.D6().g3()});
g.Y8.prototype.g3=g.Cc(18,function(){return this.app.md()});
g.NC.prototype.g3=g.Cc(17,function(){return this.sx.g3()});
g.s9.prototype.g3=g.Cc(16,function(){var a;return((a=this.LO)==null?void 0:a.md())||null});
g.fS.prototype.g3=g.Cc(15,function(){return null});
g.wX.prototype.VH=g.Cc(1,function(a){return(a=this.xb(a))?a.V:0});
g.kV.prototype.VH=g.Cc(0,function(){return 0});
var BbQ=/#(.)(.)(.)/,lRf=/^#(?:[0-9a-f]{3}){1,2}$/i,Gnj={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};CL.prototype.contains=function(a){a=g.Po(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
CL.prototype.length=function(){return this.segments.length/2};
g.u(YEG,g.S);g.H=YEG.prototype;g.H.Bs=function(){g.S.prototype.Bs.call(this);this.B&&this.B.cancel()};
g.H.T1=function(){this.seekTo(this.player.getCurrentTime())};
g.H.seekTo=function(a){a-=this.player.Dl();var I=this.V;this.V=g.no(this.Va.eC(a).nO);I!==this.V&&this.j&&this.j()};
g.H.reset=function(){this.J=new CL;this.Y=-1;this.B&&(this.B.cancel(),this.B=null)};
g.H.eJ=function(){this.Ox();var a;if(a=this.V!=null)a=this.V,a=a.V.Uy(a);if(a&&!this.B&&!(this.V&&this.V.startTime-this.player.getCurrentTime()>30)){a=this.V;a=g.O(a.V.Ql(a));var I=a.nO[0],U;if((U=this.player.getVideoData())==null?0:U.enableServerStitchedDai)if(U=this.player.g3()){var e=I.V.info.id,T=I.pO,C=a.nO[0].J;if(this.policy.Ux){if(U=U.Bq(C,T,e,3))a.J=U}else if(e=U.dE(C,T,e,3))if(U=U.a7(T),U===0)e&&(a.V=new g.YB(e));else if(U===2){this.C.start();OXJ(this)&&this.seekTo(this.player.getCurrentTime());
return}}I.V.index.IV(I.pO)?(this.J.contains(a.nO[0].pO)||SEj(this,a),this.V=g.no(a.nO)):OXJ(this)&&this.seekTo(this.player.getCurrentTime())}this.C.start()};
g.u(rQ,g.bD);g.H=rQ.prototype;g.H.MO=function(a,I,U){var e=this;this.S6();I=EOQ(this,a.getId());I||(I=a.languageCode,I=this.V.isManifestless?dSo(this,I,"386"):dSo(this,I));if(I){var T=(I.index.VH(I.index.Ra())-I.index.getStartTime(I.index.Ra()))*1E3,C=this.K.X(),r=new g.igc(C),q=function(){e.B&&e.B.reset();e.Y=!0};
C.N("html5_keep_caption_data_after_seek")&&(q=null);this.B=new YEG(r,this.K,I,function(x,Z){U.xz(x,a,Z,T)},this.C||g.eG(I.info),q)}};
g.H.hP=function(){var a=this.Y;this.Y=!1;return a};
g.H.qQ=function(a){var I=this.K.X().N("html5_fallback_if_rawcc_missing");var U=this.V.V.rawcc!=null;if(!this.C||!U&&I)I=this.V.isManifestless?ymd(this,"386"):ymd(this);else{if(!U){this.logger.V(386248249,"rawcc used but unavailable");return}I=[new g.Mh({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Mh({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}I=g.k(I);
for(U=I.next();!U.done;U=I.next())g.Ku(this.L,U.value);a.F9()};
g.H.S6=function(){this.B&&(this.B.dispose(),this.B=null)};
g.H.BI=function(){return""};
g.H.NR=function(){this.B&&(this.B.reset(),this.K.HE("captions"))};
var LL=/^#(?:[0-9a-f]{3}){1,2}$/i;var F5z=["left","right","center","justify"];g.u(Hs,g.F);g.H=Hs.prototype;g.H.q4=function(a,I){this.Z6=a;this.XX=I;var U=g.hO(this.element,this.element.parentElement);this.xa=a-U.x;this.i5=I-U.y};
g.H.yU=function(a,I){if(a!==this.Z6||I!==this.XX){g.qI(this.element,"ytp-dragging")||g.x5(this.element,"ytp-dragging");var U=g.oD(this.element);a=a-this.xa-.02*this.playerWidth;var e=I-this.i5-.02*this.playerHeight,T=(a+U.width/2)/this.maxWidth*3;T=Math.floor(g.WA(T,0,2));var C=(e+U.height/2)/this.maxHeight*3;C=Math.floor(g.WA(C,0,2));I=T+C*3;a=(a+T/2*U.width)/this.maxWidth;a=g.WA(a,0,1)*100;U=(e+C/2*U.height)/this.maxHeight;U=g.WA(U,0,1)*100;this.L.params.Tw=I;this.L.params.Z4=U;this.L.params.Sl=
a;this.L.params.isDefault=!1;this.V.Tw=I;this.V.Z4=U;this.V.Sl=a;this.V.isDefault=!1;this.gw.Tw=I;this.gw.Z4=U;this.gw.Sl=a;this.gw.isDefault=!1;this.D8()}};
g.H.rl=function(){g.ta(this.element,"ytp-dragging")};
g.H.D8=function(){this.MA(this.C)};
g.H.getType=function(){return this.type};
g.H.MA=function(a){var I=this.E7?0:Math.min(this.KZ(),this.maxWidth),U=this.t6(),e=this.E7;if(e){var T=getComputedStyle(this.J.parentNode);T=qp(T.borderLeftWidth)+qp(T.borderRightWidth)+qp(T.paddingLeft)+qp(T.paddingRight)}else T=0;var C=T;T="";this.L.params.mH===3&&(T="rotate(180deg)");var r=e?"calc(96% - "+C+"px)":"96%";g.Gr(this.element,{top:0,left:0,right:"",bottom:"",width:I?I+"px":"",height:U?U+"px":"","max-width":r,"max-height":r,margin:"",transform:""});this.z6(a);T={transform:T,top:"",left:"",
width:I?I+"px":"",height:U?U+"px":"","max-width":"","max-height":""};var q=this.V.Sl*.96+2;r=this.V.Tw;switch(r){case 0:case 3:case 6:(e=this.V.Ao.fontSizeIncrement)&&e>0&&this.V.mH!==2&&this.V.mH!==3&&(q=Math.max(q/(1+e*2),2));T.left=q+"%";break;case 1:case 4:case 7:T.left=q+"%";q=this.J.offsetWidth;I||q?(I=I||q+1,T.width=I+"px",T["margin-left"]=e?I/-2-C/2+"px":I/-2+"px"):T.transform+=" translateX(-50%)";break;case 2:case 5:case 8:T.right=100-q+"%"}e=this.V.Z4*.96+2;switch(r){case 0:case 1:case 2:T.top=
e+"%";break;case 3:case 4:case 5:T.top=e+"%";(U=U||this.element.clientHeight)?(T.height=U+"px",T["margin-top"]=U/-2+"px"):T.transform+=" translateY(-50%)";break;case 6:case 7:case 8:T.bottom=100-e+"%"}g.Gr(this.element,T);if(this.Y){U=this.J.offsetHeight;e=1;for(I=0;I<a.length;I++)T=a[I],typeof T.text==="string"&&(e+=T.text.split("\n").length-1,T.append||I===0||e++);U/=e;this.Y.style.height=U+"px";this.Y.style.width=U+"px";this.element.style.paddingLeft=U+5+"px";this.element.style.paddingRight=U+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-U-5;U=Number(this.element.style.marginRight.replace("px",""))-U-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=U+"px"}};
g.H.z6=function(a){var I;for(I=0;I<a.length&&a[I]===this.C[I];I++);if(this.dw||this.C.length>I)I=0,this.dw=!1,this.C=[],this.D=this.zt=this.Ux=null,g.sJ(this.J);for(;I<a.length;I++)Nbm(this,a[I])};
g.H.KZ=function(){return 0};
g.H.t6=function(){return 0};
g.H.toString=function(){return g.F.prototype.toString.call(this)};DSd.prototype.clear=function(){this.B=this.time=this.mode=0;this.V=[];this.reset()};
DSd.prototype.reset=function(){this.mode=0;this.J.reset(0);this.U.reset(1)};
var vOJ=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];xC.prototype.set=function(a){this.type=a};
xC.prototype.get=function(){return this.type};
Zd.prototype.clear=function(){this.state=0};
Zd.prototype.update=function(){this.state=this.state===2?1:0};
Zd.prototype.qJ=function(){return this.state!==0};
Zd.prototype.matches=function(a,I){return this.qJ()&&a===this.MH&&I===this.aO};
ewo.prototype.reset=function(){this.timestamp=this.V=0};
tI.prototype.updateTime=function(a){for(var I=1;I<=15;++I)for(var U=1;U<=32;++U)this.B[I][U].timestamp=a};
tI.prototype.debugString=function(){for(var a="\n",I=1;I<=15;++I){for(var U=1;U<=32;++U){var e=this.B[I][U];a=e.V===0?a+"_":a+String.fromCharCode(e.V)}a+="\n"}return a};
tI.prototype.reset=function(a){for(var I=0;I<=15;I++)for(var U=0;U<=32;U++)this.B[I][U].reset();this.J=a;this.V=0;this.L=this.row=1};
var TU8=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Cp4=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],rOQ=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Hzz=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];t2Q.prototype.reset=function(a,I){this.U=I;this.style.set(2);this.L=this.Y;this.J=this.C;this.V=this.L;var U=(a<<2)+(I<<1);this.Y.reset(U);this.C.reset(U);this.text.reset((a<<2)+(I<<1)+1)};
oOI.prototype.reset=function(a){this.U=a;this.L.clear();this.J=this.B;this.B.reset(a,0);this.Y.reset(a,1)};JOj.prototype.J=function(){};g.u(ux,g.qA);ux.prototype.toString=function(){return g.qA.prototype.toString.call(this)};g.u(kC,g.S);kC.prototype.Mm=function(){return[]};
kC.prototype.reset=function(){};g.u(V4,g.qA);V4.prototype.toString=function(){return g.qA.prototype.toString.call(this)};
var AI=0;g.u(Mp,kC);Mp.prototype.reset=function(){this.Y={};this.L=this.V=null;this.U=!0};
Mp.prototype.Mm=function(a,I){a=a.firstChild;a.getAttribute("format");I=I||0;Number.isFinite(I);a=Array.from(a.childNodes);a=g.k(a);for(var U=a.next();!U.done;U=a.next())if(U=U.value,U.nodeType===1)switch(U.tagName){case "head":var e=U;break;case "body":var T=U}if(e)for(e=Array.from(e.childNodes),e=g.k(e),a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":U=a.getAttribute("id");var C=this.pens,r={},q=a.getAttribute("p");q&&Object.assign(r,this.pens[q]);q=$C(a,"b");
q!=null&&(r.bold=q);q=$C(a,"i");q!=null&&(r.italic=q);q=$C(a,"u");q!=null&&(r.underline=q);q=ix(a,"et");q!=null&&(r.charEdgeStyle=q);q=ix(a,"of");q!=null&&(r.offset=q);q=gQ(a,"bc");q!=null&&(r.background=q);q=gQ(a,"ec");q!=null&&(r.Xp=q);q=gQ(a,"fc");q!=null&&(r.color=q);q=ix(a,"fs");q!=null&&q!==0&&(r.fontFamily=q);q=jl(a,"sz");q!==void 0&&(r.fontSizeIncrement=q/100-1);q=jl(a,"bo");q!==void 0&&(r.backgroundOpacity=q/255);q=jl(a,"fo");q!==void 0&&(r.textOpacity=q/255);q=ix(a,"rb");q!=null&&q!==10&&
q!==0&&(r.U1=q>10?q-1:q);a=ix(a,"hg");a!=null&&(r.YK=a);C[U]=r;break;case "ws":U=a.getAttribute("id");this.D[U]=AO4(this,a);break;case "wp":U=a.getAttribute("id"),this.C[U]=M2z(this,a)}if(T){e=[];T=Array.from(T.childNodes);T=g.k(T);for(a=T.next();!a.done;a=T.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.V=jDJ(this,a,I,!1);(a=this.Y[this.V.id])&&a.end>this.V.start&&(a.end=this.V.start);this.Y[this.V.id]=this.V;e.push(this.V);break;case "p":var x=a;q=I;U=[];C=x.getAttribute("w")||
this.J;r=!!$C(x,"a");q=(jl(x,"t")||0)+q;var Z=jl(x,"d")||5E3;r||(!this.U&&this.L&&this.L.windowId===C&&this.L.end>q&&(this.L.end=q),this.L&&this.L.text==="\n"&&(this.L.text=""));var t=r?6:5,n=x.getAttribute("p");n=n?this.pens[n]:null;var K=Array.from(x.childNodes);K.length&&(this.U=x.getAttribute("d")!=null);for(x=0;x<K.length;x++){var b=K[x],J=void 0;x>0&&(r=!0);var V=void 0;b.nodeType===1&&(V=b);if(V&&V.tagName==="s"){if((b=(b=V.getAttribute("p"))?this.pens[b]:null)&&b.U1&&(b.U1===1?(b=K.slice(x,
x+4),b.length===4&&(J=kro(q,Z,C,r,t,b,this.pens),x+=3)):J=kro(q,Z,C,r,t,[V],this.pens)),!J){var M=V;J=q;V=Z;b=C;var c=r,W=t,B=M.textContent?M.textContent:"",Y=M.getAttribute("p");Y=Y?this.pens[Y]:null;M=jl(M,"t")||0;J=new ux(J+M,V-M,W,b,B,c,Y)}}else J=new ux(q,Z,t,C,b.textContent||"",r,n);U.push(J);this.L=J}if(U.length>0)for(U[0].windowId===this.J&&(this.V=jDJ(this,a,I,!0),e.push(this.V)),a=g.k(U),U=a.next();!U.done;U=a.next())U=U.value,U.windowId=this.V.id,this.V.V.push(U),e.push(U)}I=e}else I=[];
return I};var HfI=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(cs,kC);cs.prototype.reset=function(){this.L.clear()};
cs.prototype.Mm=function(a,I){var U=JSON.parse(a);if(!U)return[];if(U.pens){a=0;for(var e=g.k(U.pens),T=e.next();!T.done;T=e.next()){T=T.value;var C={},r=T.pParentId;r&&Object.assign(C,g.O(this.V.get(r)));T.bAttr&&(C.bold=!0);T.iAttr&&(C.italic=!0);T.uAttr&&(C.underline=!0);r=T.ofOffset;r!=null&&(C.offset=r);T.szPenSize!==void 0&&(C.fontSizeIncrement=T.szPenSize/100-1);r=T.etEdgeType;r!=null&&(C.charEdgeStyle=r);T.ecEdgeColor!==void 0&&(C.Xp=Ws(T.ecEdgeColor));r=T.fsFontStyle;r!=null&&r!==0&&(C.fontFamily=
r);T.fcForeColor!==void 0&&(C.color=Ws(T.fcForeColor));T.foForeAlpha!==void 0&&(C.textOpacity=T.foForeAlpha/255);T.bcBackColor!==void 0&&(C.background=Ws(T.bcBackColor));T.boBackAlpha!==void 0&&(C.backgroundOpacity=T.boBackAlpha/255);(r=T.rbRuby)&&r!==10&&(C.U1=r>10?r-1:r,C.textEmphasis=HfI.get(C.U1));T.hgHorizGroup&&(C.YK=T.hgHorizGroup);this.V.set(a++,C)}}if(U.wsWinStyles)for(a=0,e=g.k(U.wsWinStyles),T=e.next();!T.done;T=e.next())T=T.value,C={},(r=T.wsParentId)?Object.assign(C,g.O(this.J.get(r))):
Object.assign(C,this.U),T.mhModeHint!==void 0&&(C.N0=T.mhModeHint),T.juJustifCode!==void 0&&(C.textAlign=T.juJustifCode),T.pdPrintDir!==void 0&&(C.mH=T.pdPrintDir),T.sdScrollDir!==void 0&&(C.Mi=T.sdScrollDir),T.wfcWinFillColor!==void 0&&(C.windowColor=Ws(T.wfcWinFillColor)),T.wfoWinFillAlpha!==void 0&&(C.windowOpacity=T.wfoWinFillAlpha/255),this.J.set(a++,C);if(U.wpWinPositions)for(a=0,e=g.k(U.wpWinPositions),T=e.next();!T.done;T=e.next())T=T.value,C={},(r=T.wpParentId)&&Object.assign(C,g.O(this.B.get(r))),
T.ahHorPos!==void 0&&(C.Sl=T.ahHorPos),T.apPoint!==void 0&&(C.Tw=T.apPoint),T.avVerPos!==void 0&&(C.Z4=T.avVerPos),T.ccCols!==void 0&&(C.QO=T.ccCols),T.rcRows!==void 0&&(C.iG=T.rcRows),this.B.set(a++,C);if(U.events){a=[];U=g.k(U.events);for(e=U.next();!e.done;e=U.next()){var q=e.value;T=(q.tStartMs||0)+I;C=q.dDurationMs||0;if(q.id)r=String(q.id),e=$1f(this,q,T,C,r),a.push(e),this.L.set(r,e);else{q.wWinId?r=q.wWinId.toString():(r="_"+AI++,e=$1f(this,q,T,C,r),a.push(e),this.L.set(r,e));e=a;var x=q;
C===0&&(C=5E3);q=g.O(this.L.get(r));var Z=!!x.aAppend,t=Z?6:5,n=x.segs,K=null;x.pPenId&&(K=g.O(this.V.get(x.pPenId)));for(x=0;x<n.length;x++){var b=n[x],J=b.utf8;if(J){var V=b.tOffsetMs||0,M=null;b.pPenId&&(M=g.O(this.V.get(b.pPenId)));if((q.params.N0!=null?q.params.N0:q.V.length>1?1:0)===2&&Z&&J==="\n")continue;b=null;var c=[],W;if(W=M&&M.U1===1){W=n;var B=x;if(B+3>=W.length||!W[B+1].pPenId||!W[B+2].pPenId||!W[B+3].pPenId)W=!1;else{var Y=W[B+1].pPenId;(Y=this.V.get(Y))&&Y.U1&&Y.U1===2?(Y=W[B+2].pPenId,
Y=this.V.get(Y),!Y||!Y.U1||Y.U1<3?W=!1:(Y=W[B+3].pPenId,W=(Y=this.V.get(Y))&&Y.U1&&Y.U1===2?!0:!1)):W=!1}}if(W)V=n[x+1].utf8,b=n[x+3].utf8,W=n[x+2].utf8,B=g.O(this.V.get(n[x+2].pPenId)),J=u7o(J,V,W,b,B),b=new ux(T,C,t,r,J,Z,M),x+=3;else{if(J.indexOf("<")>-1){var y=void 0;c=M;W=K;B=T;Y=C;var z=V,m=t,sS=Z,eb=[],v=g.O(g.Q0("<html>"+J+"</html>"));if(!v.getElementsByTagName("parsererror").length&&((y=v.firstChild)==null?0:y.childNodes.length))for(y=g.k(v.firstChild.childNodes),v=y.next();!v.done;v=y.next()){v=
v.value;var Hw=void 0,N=void 0,ML=(N=(Hw=v.textContent)==null?void 0:Hw.replace(/\n/g,""))!=null?N:"";if(v.nodeType!==3||ML&&ML.match(/^ *$/)==null){Hw={};Object.assign(Hw,c||W);N=void 0;switch((N=v)==null?void 0:N.tagName){case "b":Hw.bold=!0;break;case "i":Hw.italic=!0;break;case "u":Hw.underline=!0}eb.push(new ux(B+z,Y-z,m,q.id,ML,sS,Hw))}}c=eb}c.length||(c=[new ux(T+V,C-V,t,q.id,J,Z,M||K)])}if(c.length)for(Z=g.k(c),M=Z.next();!M.done;M=Z.next())M=M.value,e.push(M),q.V.push(M);else b&&(e.push(b),
q.V.push(b))}Z=!0}}}I=a}else I=[];return I};g.u(lx,g.bD);lx.prototype.MO=function(a,I,U){W5D(this.videoData.videoId,a.vssId,U.xz)};
lx.prototype.qQ=function(a){if(this.audioTrack)for(var I=g.k(this.audioTrack.captionTracks),U=I.next();!U.done;U=I.next())g.Ku(this.L,U.value);a.F9()};g.u(Bs,Hs);Bs.prototype.z6=function(a){var I=this.L.V;Hs.prototype.z6.call(this,a);for(a=a.length;a<I.length;a++){var U=I[a];if(C&&U.V===T)var e=C;else{e={};Object.assign(e,U.V);Object.assign(e,qRd);var T=U.V;var C=e}Nbm(this,U,e)}};
var qRd={qxX:!0};g.u(Xt,JOj);Xt.prototype.J=function(a,I,U,e,T){if(U<e){var C="_"+AI++;U=U/1E3-this.Y;e=e/1E3-this.Y;a=new V4(U,e-U,5,C,{textAlign:0,Tw:0,Sl:I*2.5,Z4:a*5.33});T=new ux(U,e-U,5,C,T);this.L.push(a);this.L.push(T)}};
g.u(fL,kC);fL.prototype.Mm=function(a){a=new Xt(a,a.byteLength,this.L);if(izz(a)){for(;a.byteOffset<a.V.byteLength;)for(a.version===0?a.B=pL(a)*(1E3/45):a.version===1&&(a.B=pL(a)*4294967296+pL(a)),a.U=Ps(a);a.U>0;a.U--){var I=Ps(a),U=Ps(a),e=Ps(a);I&4&&(I&3)===this.track&&(this.track===0||this.track===1)&&(I=this.V,I.V.push({time:a.B,type:this.track,cC:U,EA:e,order:I.V.length}))}U1d(this.V,a);return a.L}return[]};
fL.prototype.reset=function(){this.V.clear()};g.u(YC,Hs);g.H=YC.prototype;g.H.D8=function(){g.sb(this.B8)};
g.H.f_=function(){this.element.removeEventListener("transitionend",this.f_,!1);g.ta(this.element,"ytp-rollup-mode");this.MA(this.rF,!0)};
g.H.t6=function(){return this.B?this.Va:this.j};
g.H.KZ=function(){return this.B?this.j:this.Va};
g.H.MA=function(a,I){this.rF=a;if(this.L.params.iG){for(var U=0,e=0;e<this.C.length&&U<a.length;e++)this.C[e]===a[U]&&U++;U>0&&U<a.length&&(a=this.C.concat(a.slice(U)));this.Vo=this.Va;this.j=this.Va=0;Hs.prototype.MA.call(this,a);WLd(this,I)}Hs.prototype.MA.call(this,a)};lZz.prototype.unload=function(){this.V!=null&&(this.K.removeEventListener("sabrCaptionsDataLoaded",this.V),this.V=null);this.P8=[];this.K.publish("sabrCaptionsBufferedRangesUpdated",this.P8)};
lZz.prototype.yv=function(a){return{formatId:g.CN(a.info.V.info,this.U7),pO:a.info.pO+(this.U7?0:1),startTimeMs:a.info.J*1E3,durationMs:a.info.D*1E3}};g.u(pa4,g.bD);g.H=pa4.prototype;g.H.MO=function(a,I,U){this.S6();I=a.getId();I=I!=null&&I in this.V.V?this.V.V[I]:null;I||(I=a.languageCode,I=this.V.isManifestless?Y8J(this,I,"386"):Y8J(this,I));I&&(this.B=a,this.Y=I,PpD(this.C,U),this.K.publish("sabrCaptionsTrackChanged",g.CN(I.info,this.V.U7)))};
g.H.qQ=function(a){var I=this.V.isManifestless?fZm(this,"386"):fZm(this);I=g.k(I);for(var U=I.next();!U.done;U=I.next())g.Ku(this.L,U.value);a.F9()};
g.H.S6=function(){this.B&&(this.B=this.Y=null,this.C.unload(),this.K.publish("sabrCaptionsTrackChanged",null))};
g.H.BI=function(){return""};
g.H.NR=function(){this.K.HE("captions")};var S8d="WEBVTT".split("").map(function(a){return a.charCodeAt(0)});
g.u(Oo,kC);
Oo.prototype.Mm=function(a,I){a instanceof ArrayBuffer&&(a=g.pU(new Uint8Array(a)));var U=[];a=a.split(xfz);for(var e=1;e<a.length;e++){var T=a[e],C=I;if(T!==""&&!Zfj.test(T)){var r=taf.exec(T);if(r&&r.length>=4){var q=Efj(r[1]),x=Efj(r[2])-q;q+=C;var Z=(r=r[3])?r.split(" "):[];r={};var t=null;var n="";var K=null,b="";Z=g.k(Z);for(var J=Z.next();!J.done;J=Z.next())if(J=J.value.split(":"),J.length===2){var V=J[1];switch(J[0]){case "line":J=V.split(",");J[0].endsWith("%")&&(t=J[0],r.Z4=Number.parseInt(t,10),
J.length===2&&(n=J[1].trim()));break;case "position":J=V.split(",");K=J[0];r.Sl=Number.parseInt(K,10);J.length===2&&(b=J[1].trim());break;case "align":switch(V){case "start":r.textAlign=0;break;case "middle":r.textAlign=2;break;case "end":r.textAlign=1}}}t||n||(n="end");if(!K)switch(r.textAlign){case 0:r.Sl=0;break;case 1:r.Sl=100;break;case 2:r.Sl=50}if(r.textAlign!=null){t=0;switch(n){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(b){case "line-left":t+=0;break;case "center":t+=
1;break;case "line-right":t+=2;break;default:switch(r.textAlign){case 0:t+=0;break;case 2:t+=1;break;case 1:t+=2}}n=t<0||t>8?7:t;r.Tw=n}T=T.substring(taf.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");b=r;r=T;T={};if(r.indexOf("<")<0&&r.indexOf("&")<0)C=d1J(q,x,5,b),x=new ux(q,x,5,C.id,r,!1,g.vo(T)?void 0:T),U.push(C),U.push(x),C.V.push(x);else for(n=r.split(nzm),n.length===1?(r=5,b=d1J(q,x,r,b)):(t=r=6,b=Object.assign({QO:32},b),b=new V4(q,x,t,"_"+AI++,b)),U.push(b),t=q,K=0;K<n.length;K++)Z=n[K],
K%2===0?(J=g.O(g.Q0("<html>"+Z+"</html>")),J.getElementsByTagName("parsererror").length?(V=J.createElement("span"),V.appendChild(J.createTextNode(Z))):V=J.firstChild,yOo(this,t,x-(t-q),r,b,K>0,V,T,U)):t=Efj(Z)+C}taf.lastIndex=0}}return U};
var Zfj=/^NOTE/,xfz=/(?:\r\n|\r|\n){2,}/,taf=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),nzm=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.BL.TO(Oo,{Mm:"wvppt"});g.u(Sl,g.S);
Sl.prototype.Mm=function(a,I,U,e){e=e||0;U=waz(this,a,U||0);a=[];try{for(var T=g.k(U),C=T.next();!C.done;C=T.next()){var r=C.value,q=r.trackData,x=r.Hm,Z=this.Ex.N("safari_live_drm_captions_fix");if(typeof q!=="string"){U=a;var t=U.concat;if(Z&&GrD(q))var n=FL8(this,q,x);else{var K=I,b=q,J=x,V=e;if(!LLJ(b))throw Error("Invalid binary caption track data");this.V||(this.V=new fL(V,K));n=this.V.Mm(b,J)}var M=t.call(U,n)}else{if(q.substring(0,6)==="WEBVTT")var c=a.concat(FL8(this,q,x));else{U=a;var W=
U.concat;a:{K=I;if(q[0]==="{")try{this.V||(this.V=new cs(m18(K)));var B=this.V.Mm(q,x);break a}catch(eb){g.d1(eb);B=[];break a}var Y=g.Q0(q);if(!Y||!Y.firstChild){var y=Error("Invalid caption track data");y.params=q;throw y;}if(Y.firstChild.tagName==="timedtext"){if(Number(Y.firstChild.getAttribute("format"))===3){b=Y;this.V||(this.V=new Mp(m18(K),this.Ex));B=this.V.Mm(b,x);break a}var z=Error("Unsupported subtitles format in web player (Format2)");z.params=q;throw z;}if(Y.firstChild.tagName==="transcript"){var m=
Error("Unsupported subtitles format in web player (Format1)");m.params=q;throw m;}var sS=Error("Invalid caption track data");sS.params=q;throw sS;}c=W.call(U,B)}M=c}a=M}return a}catch(eb){return this.logger.V(187101178,"Captions parsing failed: "+eb.message+". "),this.clear(),[]}};
Sl.prototype.clear=function(){this.V&&this.V.dispose();this.V=null};
Sl.prototype.reset=function(){this.V&&this.V.reset()};
Sl.prototype.Bs=function(){g.S.prototype.Bs.call(this);this.clear()};var Q4={windowColor:"#080808",windowOpacity:0,textAlign:2,Tw:7,Sl:50,Z4:100,isDefault:!0,Ao:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(GN,g.nu);g.H=GN.prototype;g.H.Bs=function(){if(this.U||this.dw){var a=this.K.K4();a&&!a.Ox()&&a.Z1()}else rez(this,!1);g.nu.prototype.Bs.call(this)};
g.H.Jq=function(){return this.Ex.N("html5_honor_caption_availabilities_in_audio_track")&&this.J!=="LIVE"&&this.J!=="SABR_LIVE"};
g.H.zZ=function(){if(this.Z6)return this.U||this.dw;var a=this.getAudioTrack();if(this.Jq()){if(!a.captionTracks.length)return!1;if(!this.V)return!0}a=iXz(a,g.eI(this.Ex));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?y4(this):NU8(this)||y4(this)?!0:ofz(this)};
g.H.load=function(){g.nu.prototype.load.call(this);this.j=this.getAudioTrack();if(this.V)this.L&&(this.XX.clear(),this.U?vfo(this,!0):this.player.getPresentingPlayerType()!==3&&this.V.MO(this.L,"json3",this.hN),this.U||this.dw||Rz(this)||this.player.s9("captionschanged",g.$l(this.L)));else{var a;this.J==="OFFLINE"?a=new lx(this.player,this.videoData,this.getAudioTrack()):this.J==="SABR_LIVE"?a=new pa4(this.videoData.V,this.player):this.J==="LIVE"?a=new rQ(this.videoData.V,this.player):this.J==="INNERTUBE"?
a=new g.Jh(this.player,this.videoData,this.getAudioTrack()):a=new g.kW(this.player,this.videoData.q2,this.videoData.videoId,g.ACb(this.videoData),this.videoData.OS,this.videoData.eventId);this.V=a;g.E(this,this.V);this.V.qQ(this.hN)}};
g.H.unload=function(){this.U&&this.L?vfo(this,!1):(this.CO&&g.Ub(this.CO),this.player.HE("captions"),this.Ux=[],this.V&&this.V.S6(),this.XX.clear(),this.Va&&this.player.xw(this.Va),this.mI());g.nu.prototype.unload.call(this);this.player.wp();this.player.s9("captionschanged",{})};
g.H.create=function(){this.zZ()&&this.load();var a;a:{var I,U,e;if(this.Ex.N("web_player_nitrate_promo_tooltip")&&((I=this.videoData.getPlayerResponse())==null?0:(U=I.captions)==null?0:(e=U.playerCaptionsTracklistRenderer)==null?0:e.enableTouchCaptionsNitrate)){var T,C;if(I=(a=this.videoData.getPlayerResponse())==null?void 0:(T=a.captions)==null?void 0:(C=T.playerCaptionsTracklistRenderer)==null?void 0:C.captionTracks)for(a=g.k(I),T=a.next();!T.done;T=a.next())if(T=T.value,T.kind==="asr"&&T.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.K.publish("showpromotooltip",this.C.element)};
g.H.F9=function(){var a=iXz(this.player.getAudioTrack(),g.eI(this.Ex));var I=a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?dQ(this,this.D):a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&y4(this)?Eo(this):NU8(this)||this.D||ofz(this)?dQ(this,this.D):y4(this)?Eo(this):null;if(this.U||this.dw){var U=g.aP(this.V.L,!0);a=[];for(var e=0;e<U.length;e++){var T=U[e],C=g.vA("TRACK");C.setAttribute("kind","subtitles");C.setAttribute("label",g.jI(T));C.setAttribute("srclang",g.iq(T));C.setAttribute("id",T.toString());
this.dw||C.setAttribute("src",this.V.BI(T,"vtt"));T===I&&C.setAttribute("default","1");a.push(C)}I=this.K.K4();I.M5(a);a=g.O(I.oF());this.Vo&&this.tU.G(a.textTracks,"change",this.Pcw)}else!this.L&&I&&mc(this,I),this.player.s9("onCaptionsTrackListChanged"),this.player.rA("onApiChange")};
g.H.Pcw=function(){for(var a=g.O(this.K.K4().oF()).textTracks,I=null,U=0;U<a.length;U++)if(a[U].mode==="showing")a:{I=g.aP(this.V.L,!0);for(var e=0;e<I.length;e++)if(I[e].toString()===a[U].id){I=I[e];break a}I=null}(this.loaded?this.L:null)!==I&&mc(this,I,!0)};
g.H.wBg=function(){!this.L&&this.U||this.unload()};
g.H.xz=function(a,I,U,e){if(a){var T;IkJ(this,(T=this.L)!=null?T:void 0);this.V.hP()&&(this.Ux=[],this.K.HE("captions"),TN(this.zt),this.XX.reset());if(this.videoData.BE){var C;U=((C=U)!=null?C:0)+this.videoData.BE}a=this.XX.Mm(a,I,U,e);if(this.xa)for(I=g.k(a),U=I.next();!U.done;U=I.next())U=U.value,U.B=this.videoData.clientPlaybackNonce,U.gU=this.videoData.BE;I=!this.Ex.N("html5_keep_caption_data_after_seek")&&(this.J==="LIVE"||this.J==="SABR_LIVE");this.player.xw(a,void 0,I);!this.D||this.dw||Rz(this)||
g.Pj(this.Ex)||g.Rd(this.Ex)||g.FT(this.Ex)||this.Ex.dw==="shortspage"||this.player.isInline()||(g.Ub(this.CO),a=V2I({Tw:0,Sl:5,Z4:5,iG:2,textAlign:0,mH:0,lang:"en"}),this.a$=[a],I=["Click "," for settings"],this.i5||(U=new g.kp(g.Oa()),g.E(this,U),this.i5=U.element),U=a.end-a.start,(e=g.jI(this.L))&&this.a$.push(new ux(a.start,U,0,a.id,e)),this.a$.push(new ux(a.start,U,0,a.id,I[0]),new ux(a.start,U,0,a.id,this.i5,!0),new ux(a.start,U,0,a.id,I[1],!0)),this.player.xw(this.a$),g.Ik(this.CO));!this.D||
this.dw||Rz(this)||(g.eI(this.Ex)?wQ(this,!0):Ft(this,!0),this.j&&(this.j.J=this.L),this.player.wp());this.D=!1}};
g.H.onCueRangeEnter=function(a){this.Ux.push(a);TN(this.zt)};
g.H.onCueRangeExit=function(a){g.Az(this.Ux,a);this.V instanceof rQ&&this.V.C&&this.player.L1([a]);TN(this.zt)};
g.H.getCaptionWindowContainerId=function(){return this.C.element.id};
g.H.XZg=function(){CHQ(this,this.a$);this.a$=null};
g.H.Sg=function(){var a=this;if(!this.B8||!this.U){this.zt.stop();g.Ocs(this.fO);this.Ux.sort(g.xM);var I=this.Ux;if(this.Va){var U=g.Sa(I,function(C){return this.Va.indexOf(C)===-1},this);
U.length&&(I=U)}I=g.k(I);for(U=I.next();!U.done;U=I.next())Ufo(this,U.value);I=g.k(Object.entries(this.e8));var e=I.next();for(U={};!e.done;U={Pr:void 0,AB:void 0},e=I.next()){var T=g.k(e.value);e=T.next().value;T=T.next().value;U.Pr=e;U.AB=T;this.fO[U.Pr]?(U.AB.element.parentNode||(U.AB instanceof YC||U.AB instanceof Bs||g.FQ(this.e8,function(C){return function(r,q){q!==C.Pr&&r.L.params.Tw===C.AB.L.params.Tw&&r.L.params.Sl===C.AB.L.params.Sl&&r.L.params.Z4===C.AB.L.params.Z4&&(r.dispose(),delete a.e8[q]);
return q===C.Pr}}(U),this),this.C.element.appendChild(U.AB.element)),U.AB.MA(this.fO[U.Pr])):(U.AB.dispose(),delete this.e8[U.Pr])}}};
g.H.mFw=function(){zw4(this,{},!0);this.player.s9("captionssettingschanged")};
g.H.x9=function(){var a=Q4.Ao;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:Q4.windowColor,windowOpacity:Q4.windowOpacity};var I=pPG()||{};I.background!=null&&(a.background=I.background);I.backgroundOverride!=null&&(a.backgroundOverride=I.backgroundOverride);I.backgroundOpacity!=null&&(a.backgroundOpacity=
I.backgroundOpacity);I.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=I.backgroundOpacityOverride);I.charEdgeStyle!=null&&(a.charEdgeStyle=I.charEdgeStyle);I.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=I.charEdgeStyleOverride);I.color!=null&&(a.color=I.color);I.colorOverride!=null&&(a.colorOverride=I.colorOverride);I.fontFamily!=null&&(a.fontFamily=I.fontFamily);I.fontFamilyOverride!=null&&(a.fontFamilyOverride=I.fontFamilyOverride);I.fontSizeIncrement!=null&&(a.fontSizeIncrement=
I.fontSizeIncrement);I.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=I.fontSizeIncrementOverride);I.fontStyle!=null&&(a.fontStyle=I.fontStyle);I.fontStyleOverride!=null&&(a.fontStyleOverride=I.fontStyleOverride);I.textOpacity!=null&&(a.textOpacity=I.textOpacity);I.textOpacityOverride!=null&&(a.textOpacityOverride=I.textOpacityOverride);I.windowColor!=null&&(a.windowColor=I.windowColor);I.windowColorOverride!=null&&(a.windowColorOverride=I.windowColorOverride);I.windowOpacity!=null&&
(a.windowOpacity=I.windowOpacity);I.windowOpacityOverride!=null&&(a.windowOpacityOverride=I.windowOpacityOverride);return a};
g.H.bK=function(a,I){var U={};Object.assign(U,pPG());Object.assign(U,a);zw4(this,U,I);this.player.s9("captionssettingschanged")};
g.H.mI=function(){!this.U&&this.loaded&&(g.dd(this.e8,function(a,I){a.dispose();delete this.e8[I]},this),this.Sg())};
g.H.BB=function(a,I){switch(a){case "fontSize":if(isNaN(I))break;a=g.WA(I,-2,4);this.bK({fontSizeIncrement:a});return a;case "reload":I&&!this.U&&mc(this,this.L,!0);break;case "stickyLoading":I!==void 0&&this.Ex.C&&(g.eI(this.Ex)?wQ(this,!!I):Ft(this,!!I));break;case "track":return Tem(this,I);case "tracklist":return this.V?g.FX(g.aP(this.V.L,!(!I||!I.includeAsr)),function(U){return g.$l(U)}):[];
case "translationLanguages":return this.V?this.V.U.map(function(U){return Object.assign({},U)}):[];
case "sampleSubtitles":this.U||I===void 0||rez(this,!!I);break;case "sampleSubtitlesCustomized":this.U||rez(this,!!I,I);break;case "recommendedTranslationLanguages":return g.sN();case "defaultTranslationSourceTrackIndices":return this.V?this.V.D:[]}};
g.H.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Ex.C&&a.push("stickyLoading");return a};
g.H.h2=function(){var a=this.L;if(this.K.Cr("captions")){if(this.Ex.N("html5_modify_caption_vss_logging")){var I;return(a=(I=this.videoData.tE)!=null?I:null)?{cc:g.Snq(a)}:{}}if(a)return I=a.vssId,a.translationLanguage&&I&&(I="t"+I+"."+g.iq(a)),{cc:I}}return{}};
g.H.LHw=function(){this.isSubtitlesOn()?(g.eI(this.Ex)?wQ(this,!1):Ft(this,!1),IkJ(this),mc(this,null,!0)):this.IU()};
g.H.IU=function(){var a=Rz(this)||!this.L?dQ(this,!0):this.L;a&&this.cX(a.vssId,"m");this.isSubtitlesOn()||mc(this,Rz(this)||!this.L?dQ(this,!0):this.L,!0)};
g.H.isSubtitlesOn=function(){return!!this.loaded&&!!this.L&&!Rz(this)};
g.H.kCg=function(){var a=Rz(this);y4(this,a)?mc(this,this.getAudioTrack().V,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Jq()&&(this.D=!1,this.L=null,this.V&&(this.V.dispose(),this.V=null)),this.zZ()&&(a?mc(this,dQ(this,!1),!1):this.load()))};
g.H.Ec=function(a){a&&(this.gw={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.C.element.style.top=this.gw.top*100+"%",this.C.element.style.left=this.gw.left*100+"%",this.C.element.style.width=this.gw.width*100+"%",this.C.element.style.height=this.gw.height*100+"%",this.C.element.style.position="absolute",a=ePd(this))&&(this.C.element.style.width=a.width+"px",this.C.element.style.height=a.height+"px")};
g.H.onVideoDataChange=function(a,I){a==="newdata"&&(this.videoData=I,this.loaded&&this.unload(),this.D=!1,this.L=null,this.V&&(this.V.dispose(),this.V=null,this.player.s9("captionschanged",{})),this.zZ()&&this.load())};
g.H.getAudioTrack=function(){return this.xa&&this.player.getPresentingPlayerType()===2?this.videoData.eX:this.player.getAudioTrack()};
g.H.mDX=function(){var a=this.K.K4();a&&!a.Ox()&&a.Z1();this.K.isFullscreen()?(this.U=this.Z6=!0,this.loaded&&this.F9()):(this.Z6=this.Ex.controlsType==="3",this.U=QDz(this));mc(this,this.L)};
g.H.Uc=function(){var a,I,U,e=(a=this.videoData.getPlayerResponse())==null?void 0:(I=a.captions)==null?void 0:(U=I.playerCaptionsTracklistRenderer)==null?void 0:U.openTranscriptCommand;e&&this.player.I$("innertubeCommand",e)};
g.H.hS=function(a,I,U){var e=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,T="";a&&(T=a.vssId,T=T.replace(e,""));var C="";a&&a.getId()&&(C=a.getId()||"");a&&a.getXtags()&&(a=a.getXtags(),a=a.replace(e,""),C=C.concat(";"+a));this.K.hS(I?T:"",I?C:"",U)};
g.H.cX=function(a,I){a=(a||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");a.length>0&&this.K.cX(a,I)};
g.H.NR=function(){this.V&&this.V.NR()};
g.BL.TO(GN,{Sg:"smucd"});g.th("captions",GN);})(_yt_player);
