(function(g){var window=this;'use strict';var Pp=function(a,I){g.F.call(this,{W:"button",ww:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],S:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},Z:[{W:"svg",S:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},Z:[{W:"g",S:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},Z:[{W:"g",S:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
Z:[{W:"path",S:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.K=a;this.listen("click",this.onClick,this);this.updateValue("title",g.fh(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.P6(I.Rd(),this.element))},aOD=function(a){g.F.call(this,
{W:"div",
T:"ytp-miniplayer-ui"});this.Y=!1;this.player=a;this.G(a,"minimized",this.GQ);this.G(a,"onStateChange",this.DVn);this.G(a,"documentpictureinpicturechange",this.MMw)},IOj=function(a,I){g.KC(a.player.getRootNode(),"ytp-player-minimized",I)},snf=function(a){g.nu.call(this,a);
this.L=new g.Ru(this);this.V=new aOD(this.player);this.V.hide();g.w4(this.player,this.V.element,4);a.isMinimized()&&(this.load(),g.KC(a.getRootNode(),"ytp-player-minimized",!0))};
g.u(Pp,g.F);Pp.prototype.onClick=function(){this.K.I$("onExpandMiniplayer")};g.u(aOD,g.F);g.H=aOD.prototype;
g.H.show=function(){this.V=new g.oj(this.Ap,null,this);this.V.start();if(!this.Y){this.tooltip=new g.ia(this.player,this);g.E(this,this.tooltip);g.w4(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Qi=new g.RP(this.player);g.E(this,this.Qi);this.progressBar=new g.pA(this.player,this);g.E(this,this.progressBar);g.w4(this.player,this.progressBar.element,4);this.L=new g.F({W:"div",T:"ytp-miniplayer-scrim"});g.E(this,this.L);this.L.KO(this.element);this.G(this.L.element,"click",this.Hg);
var a=new g.F({W:"button",ww:["ytp-miniplayer-close-button","ytp-button"],S:{"aria-label":"Close"},Z:[g.ld()]});g.E(this,a);a.KO(this.L.element);this.G(a.element,"click",this.Gh);a=new Pp(this.player,this);g.E(this,a);a.KO(this.L.element);this.B=new g.F({W:"div",T:"ytp-miniplayer-controls"});g.E(this,this.B);this.B.KO(this.L.element);this.G(this.B.element,"click",this.Hg);var I=new g.F({W:"div",T:"ytp-miniplayer-button-container"});g.E(this,I);I.KO(this.B.element);a=new g.F({W:"div",T:"ytp-miniplayer-play-button-container"});
g.E(this,a);a.KO(this.B.element);var U=new g.F({W:"div",T:"ytp-miniplayer-button-container"});g.E(this,U);U.KO(this.B.element);this.D=new g.Wi(this.player,this,!1);g.E(this,this.D);this.D.KO(I.element);I=new g.ci(this.player,this);g.E(this,I);I.KO(a.element);this.nextButton=new g.Wi(this.player,this,!0);g.E(this,this.nextButton);this.nextButton.KO(U.element);this.C=new g.tN(this.player,this,0);g.E(this,this.C);this.C.KO(this.L.element);this.J=new g.F({W:"div",T:"ytp-miniplayer-buttons"});g.E(this,
this.J);g.w4(this.player,this.J.element,4);a=new g.F({W:"button",ww:["ytp-miniplayer-close-button","ytp-button"],S:{"aria-label":"Close"},Z:[g.ld()]});g.E(this,a);a.KO(this.J.element);this.G(a.element,"click",this.Gh);a=new g.F({W:"button",ww:["ytp-miniplayer-replay-button","ytp-button"],S:{"aria-label":"Close"},Z:[g.Yp()]});g.E(this,a);a.KO(this.J.element);this.G(a.element,"click",this.R3t);a=new Pp(this.player,this);g.E(this,a);a.KO(this.J.element);this.G(this.player,"presentingplayerstatechange",
this.Jp);this.G(this.player,"appresize",this.jj);this.G(this.player,"fullscreentoggled",this.jj);this.jj();this.Y=!0}this.player.getPlayerState()!==0&&g.F.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.H.hide=function(){this.V&&(this.V.dispose(),this.V=void 0);g.F.prototype.hide.call(this);this.player.isMinimized()||(this.Y&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.H.Bs=function(){this.V&&(this.V.dispose(),this.V=void 0);g.F.prototype.Bs.call(this)};
g.H.Gh=function(){this.player.N("kevlar_watch_while_v2")||this.player.stopVideo();this.player.I$("onCloseMiniplayer")};
g.H.R3t=function(){this.player.playVideo()};
g.H.Hg=function(a){if(a.target===this.L.element||a.target===this.B.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.H.GQ=function(){IOj(this,this.player.isMinimized())};
g.H.MMw=function(){IOj(this,this.player.DJ());g.KC(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.DJ())};
g.H.mP=function(){this.progressBar.Cv();this.C.Cv()};
g.H.Ap=function(){this.mP();this.V&&this.V.start()};
g.H.Jp=function(a){g.Q(a.state,32)&&this.tooltip.hide()};
g.H.jj=function(){var a=this.player.j8().getPlayerSize().width;g.rIi(this.progressBar,0,a,!1);g.fA(this.progressBar)};
g.H.DVn=function(a){this.player.isMinimized()&&(a===0?this.hide():this.show())};
g.H.Rd=function(){return this.tooltip};
g.H.t0=function(a,I,U,e,T){var C=0,r=0,q=0,x=g.oD(a);e=I&&(g.qI(I,"ytp-prev-button")||g.qI(I,"ytp-next-button"));if(I){U=g.qI(I,"ytp-play-button");var Z=g.qI(I,"ytp-miniplayer-expand-watch-page-button");e?C=q=12:U?(I=g.hO(I,this.element),q=I.x,C=I.y-12):Z&&(q=g.qI(I,"ytp-miniplayer-button-top-left"),C=g.hO(I,this.element),I=g.oD(I),q?(q=8,C=C.y+40):(q=C.x-x.width+I.width,C=C.y-20))}else q=U-x.width/2,r=25+(T||0);I=this.player.j8().getPlayerSize();T=C+(T||0);x=g.WA(q,0,I.width-x.width-12);T?(a.style.top=
T+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=r+"px");a.style.left=x+"px";r=g.qI(a,"ytp-preview");a.style.visibility=e&&r&&I.height<225?"hidden":""};g.u(snf,g.nu);g.H=snf.prototype;g.H.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),I=16/9;a=a>I+.1||a<I-.1;g.KC(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.H.create=function(){g.nu.prototype.create.call(this);this.L.G(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.H.hj=function(){return!1};
g.H.load=function(){this.player.hideControls();this.V.show()};
g.H.unload=function(){this.player.showControls();this.V.hide()};g.th("miniplayer",snf);})(_yt_player);
